# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Kerkhoven2013 - Glycolysis and Pentose Phosphate Pathway in T.brucei - MODEL D in fructose medium (with ATP:ADP antiporter)."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Kerkhoven2013GlycolysisAndPentosePhosphatePBiomd0000000516Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Kerkhoven2013 - Glycolysis and Pentose Phosphate Pathway in T.brucei - MODEL D in fructose medium (with ATP:ADP antiporter)."""

    _SBML_ID = 'BIOMD0000000516'
    _TITLE = 'Kerkhoven2013 - Glycolysis and Pentose Phosphate Pathway in T.brucei - MODEL D in fructose medium (with ATP:ADP antiporter)'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'_2PGA_c': 'glycolysis_state_1', 'Fru_g': 'glycolysis_state_2', 'Fru_c': 'glycolysis_state_3', 'DHAP_c': 'glycolysis_state_4', 'ATP_g': 'glycolysis_state_5', 'DHAP_g': 'glycolysis_state_6', 'ADP_g': 'glycolysis_state_7', 'Glc6P_g': 'glycolysis_state_8', 'ADP_c': 'cytosolic_adp', '_3PGA_c': 'glycolysis_state_10', 'Fru6P_g': 'glycolysis_state_11', 'NADP_c': 'cytosolic_nadp', 'ATP_c': 'cytosolic_atp', 'NADP_g': 'glycolysis_state_14', '_6PG_g': 'glycolysis_state_15', 'Rul5P_c': 'glycolysis_state_16', '_6PG_c': 'glycolysis_state_17', 'Rul5P_g': 'glycolysis_state_18', 'Glc6P_c': 'glycolysis_state_19', '_13BPGA_g': 'glycolysis_state_20', 'Glc_c': 'cytosolic_glucose', 'Glc_g': 'glycolysis_state_22', 'NADPH_g': 'glycolysis_state_23', 'NADPH_c': 'cytosolic_nadph', 'Pyr_c': 'cytosolic_pyruvate', 'NAD_g': 'glycolysis_state_26', 'Fru16BP_g': 'glycolysis_state_27', 'GA3P_g': 'glycolysis_state_28', 'TSH2_c': 'glycolysis_state_29', 'Gly3P_c': 'glycolysis_state_30', 'Gly3P_g': 'glycolysis_state_31', '_6PGL_c': 'glycolysis_state_32', 'TS2_c': 'glycolysis_state_33', '_6PGL_g': 'glycolysis_state_34', 'PEP_c': 'cytosolic_phosphoenolpyruvate', 'AMP_g': 'glycolysis_state_36', '_3PGA_g': 'glycolysis_state_37', 'AMP_c': 'cytosolic_amp', 'NADH_g': 'glycolysis_state_39'}
    _OBSERVABLES = ['_2PGA_c', 'Fru_g', 'Fru_c', 'DHAP_c', 'ATP_g', 'DHAP_g', 'ADP_g', 'Glc6P_g', 'ADP_c', '_3PGA_c', 'Fru6P_g', 'NADP_c', 'ATP_c', 'NADP_g', '_6PG_g', 'Rul5P_c', '_6PG_c', 'Rul5P_g', 'Glc6P_c', '_13BPGA_g', 'Glc_c', 'Glc_g', 'NADPH_g', 'NADPH_c', 'Pyr_c', 'NAD_g', 'Fru16BP_g', 'GA3P_g', 'TSH2_c', 'Gly3P_c', 'Gly3P_g', '_6PGL_c', 'TS2_c', '_6PGL_g', 'PEP_c', 'AMP_g', '_3PGA_g', 'AMP_c', 'NADH_g']
    _SPECIES_LABELS = {'_2PGA_c': 'Glycolysis state 1', 'Fru_g': 'Glycolysis state 2', 'Fru_c': 'Glycolysis state 3', 'DHAP_c': 'Glycolysis state 4', 'ATP_g': 'Glycolysis state 5', 'DHAP_g': 'Glycolysis state 6', 'ADP_g': 'Glycolysis state 7', 'Glc6P_g': 'Glycolysis state 8', 'ADP_c': 'Cytosolic ADP', '_3PGA_c': 'Glycolysis state 10', 'Fru6P_g': 'Glycolysis state 11', 'NADP_c': 'Cytosolic NADP', 'ATP_c': 'Cytosolic ATP', 'NADP_g': 'Glycolysis state 14', '_6PG_g': 'Glycolysis state 15', 'Rul5P_c': 'Glycolysis state 16', '_6PG_c': 'Glycolysis state 17', 'Rul5P_g': 'Glycolysis state 18', 'Glc6P_c': 'Glycolysis state 19', '_13BPGA_g': 'Glycolysis state 20', 'Glc_c': 'Cytosolic Glucose', 'Glc_g': 'Glycolysis state 22', 'NADPH_g': 'Glycolysis state 23', 'NADPH_c': 'Cytosolic NADPH', 'Pyr_c': 'Cytosolic Pyruvate', 'NAD_g': 'Glycolysis state 26', 'Fru16BP_g': 'Glycolysis state 27', 'GA3P_g': 'Glycolysis state 28', 'TSH2_c': 'Glycolysis state 29', 'Gly3P_c': 'Glycolysis state 30', 'Gly3P_g': 'Glycolysis state 31', '_6PGL_c': 'Glycolysis state 32', 'TS2_c': 'Glycolysis state 33', '_6PGL_g': 'Glycolysis state 34', 'PEP_c': 'Cytosolic Phosphoenolpyruvate', 'AMP_g': 'Glycolysis state 36', '_3PGA_g': 'Glycolysis state 37', 'AMP_c': 'Cytosolic AMP', 'NADH_g': 'Glycolysis state 39'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_glycolysis_state_1': ('_2PGA_c', 0.1, 'native SBML value', 'Initial condition for glycolysis state 1. Maps to bundled SBML symbol `_2PGA_c`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_2': ('Fru_g', 0.1, 'native SBML value', 'Initial condition for glycolysis state 2. Maps to bundled SBML symbol `Fru_g`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_3': ('Fru_c', 0.1, 'native SBML value', 'Initial condition for glycolysis state 3. Maps to bundled SBML symbol `Fru_c`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_4': ('DHAP_c', 2.23132912, 'native SBML value', 'Initial condition for glycolysis state 4. Maps to bundled SBML symbol `DHAP_c`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_5': ('ATP_g', 0.2405, 'native SBML value', 'Initial condition for glycolysis state 5. Maps to bundled SBML symbol `ATP_g`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'glycolysis_state_1': ('_2PGA_c', 'native SBML value', 'Glycolysis state 1; conservative display label for an abstract SBML state variable. Maps to SBML symbol `_2PGA_c`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glycolysis_state_2': ('Fru_g', 'native SBML value', 'Glycolysis state 2; conservative display label for an abstract SBML state variable. Maps to SBML symbol `Fru_g`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glycolysis_state_3': ('Fru_c', 'native SBML value', 'Glycolysis state 3; conservative display label for an abstract SBML state variable. Maps to SBML symbol `Fru_c`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glycolysis_state_4': ('DHAP_c', 'native SBML value', 'Glycolysis state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `DHAP_c`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glycolysis_state_5': ('ATP_g', 'native SBML value', 'Glycolysis state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `ATP_g`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/BIOMD0000000516.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
