# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Haiman2020 - Pyruvate Kinase Regulatory Model of Erythrocyte Glycolysis."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Haiman2020PyruvateKinaseRegulatoryModelOfEModel2012150002Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Haiman2020 - Pyruvate Kinase Regulatory Model of Erythrocyte Glycolysis."""

    _SBML_ID = 'MODEL2012150002'
    _TITLE = 'Haiman2020 - Pyruvate Kinase Regulatory Model of Erythrocyte Glycolysis'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'M_glc__D_c': 'd_glucose', 'M_g6p_c': 'd_glucose_6_phosphate', 'M_f6p_c': 'd_fructose_6_phosphate', 'M_fdp_c': 'd_fructose_1_6_bisphosphate', 'M_dhap_c': 'dihydroxyacetone_phosphate', 'M_g3p_c': 'glyceraldehyde_3_phosphate', 'M__13dpg_c': 'observable_3_phospho_d_glyceroyl_phosphate', 'M__3pg_c': 'observable_3_phospho_d_glycerate', 'M__2pg_c': 'd_glycerate_2_phosphate', 'M_pep_c': 'phosphoenolpyruvate', 'M_pyr_c': 'mitochondrial_cytosolic_pyruvate', 'M_lac__L_c': 'l_lactate', 'M_nad_c': 'nicotinamide_adenine_dinucleotide', 'M_nadh_c': 'nicotinamide_adenine_dinucleotide_reduced', 'M_amp_c': 'amp', 'M_adp_c': 'adp', 'M_atp_c': 'atp', 'M_pi_c': 'phosphate', 'M_h_c': 'glycolysis_state_19', 'M_h2o_c': 'h2o', 'M__23dpg_c': 'observable_2_3_disphospho_d_glycerate', 'M_hb_1o2_c': 'oxyhemoglobin_1', 'M_hb_c': 'hemoglobin', 'M_o2_c': 'mitochondrial_cytosolic_o2', 'M_hb_2o2_c': 'oxyhemoglobin_2', 'M_hb_3o2_c': 'oxyhemoglobin_3', 'M_hb_4o2_c': 'oxyhemoglobin_4', 'M_dhb_c': 'deoxyhemoglobin', 'M_pyk_R0_P_c': 'pyk_phosphoenolpyruvate_complex', 'M_pyk_R0_c': 'glycolysis_state_30', 'M_pyk_R0_A_c': 'pyk_adp_complex', 'M_pyk_R0_AP_c': 'pyk_adp_phosphoenolpyruvate_complex', 'M_pyk_R1_c': 'pyk_fdp_complex', 'M_pyk_R1_P_c': 'pyk_phosphoenolpyruvate_fdp_complex', 'M_pyk_R1_A_c': 'pyk_adp_fdp_complex', 'M_pyk_R1_AP_c': 'pyk_adp_phosphoenolpyruvate_fdp_complex', 'M_pyk_R2_c': 'pyk_fdp_complex_2', 'M_pyk_R2_P_c': 'pyk_phosphoenolpyruvate_fdp_complex_2', 'M_pyk_R2_A_c': 'pyk_adp_fdp_complex_2', 'M_pyk_R2_AP_c': 'pyk_adp_phosphoenolpyruvate_fdp_complex_2', 'M_pyk_R3_c': 'pyk_fdp_complex_3', 'M_pyk_R3_P_c': 'pyk_phosphoenolpyruvate_fdp_complex_3', 'M_pyk_R3_A_c': 'pyk_adp_fdp_complex_3', 'M_pyk_R3_AP_c': 'pyk_adp_phosphoenolpyruvate_fdp_complex_3', 'M_pyk_R4_c': 'pyk_fdp_complex_4', 'M_pyk_R4_P_c': 'pyk_phosphoenolpyruvate_fdp_complex_4', 'M_pyk_R4_A_c': 'pyk_adp_fdp_complex_4', 'M_pyk_R4_AP_c': 'pyk_adp_phosphoenolpyruvate_fdp_complex_4', 'M_pyk_T0_c': 'glycolysis_state_49', 'M_pyk_T1_c': 'pyk_atp_complex', 'M_pyk_T2_c': 'pyk_atp_complex_2', 'M_pyk_T3_c': 'pyk_atp_complex_3', 'M_pyk_T4_c': 'pyk_atp_complex_4'}
    _OBSERVABLES = ['M_glc__D_c', 'M_g6p_c', 'M_f6p_c', 'M_fdp_c', 'M_dhap_c', 'M_g3p_c', 'M__13dpg_c', 'M__3pg_c', 'M__2pg_c', 'M_pep_c', 'M_pyr_c', 'M_lac__L_c', 'M_nad_c', 'M_nadh_c', 'M_amp_c', 'M_adp_c', 'M_atp_c', 'M_pi_c', 'M_h_c', 'M_h2o_c', 'M__23dpg_c', 'M_hb_1o2_c', 'M_hb_c', 'M_o2_c', 'M_hb_2o2_c', 'M_hb_3o2_c', 'M_hb_4o2_c', 'M_dhb_c', 'M_pyk_R0_P_c', 'M_pyk_R0_c', 'M_pyk_R0_A_c', 'M_pyk_R0_AP_c', 'M_pyk_R1_c', 'M_pyk_R1_P_c', 'M_pyk_R1_A_c', 'M_pyk_R1_AP_c', 'M_pyk_R2_c', 'M_pyk_R2_P_c', 'M_pyk_R2_A_c', 'M_pyk_R2_AP_c', 'M_pyk_R3_c', 'M_pyk_R3_P_c', 'M_pyk_R3_A_c', 'M_pyk_R3_AP_c', 'M_pyk_R4_c', 'M_pyk_R4_P_c', 'M_pyk_R4_A_c', 'M_pyk_R4_AP_c', 'M_pyk_T0_c', 'M_pyk_T1_c', 'M_pyk_T2_c', 'M_pyk_T3_c', 'M_pyk_T4_c']
    _SPECIES_LABELS = {'M_glc__D_c': 'D Glucose', 'M_g6p_c': 'D Glucose 6 Phosphate', 'M_f6p_c': 'D Fructose 6 Phosphate', 'M_fdp_c': 'D Fructose 1 6 Bisphosphate', 'M_dhap_c': 'Dihydroxyacetone Phosphate', 'M_g3p_c': 'Glyceraldehyde 3 Phosphate', 'M__13dpg_c': '3 Phospho D Glyceroyl Phosphate', 'M__3pg_c': '3 Phospho D Glycerate', 'M__2pg_c': 'D Glycerate 2 Phosphate', 'M_pep_c': 'Phosphoenolpyruvate', 'M_pyr_c': 'Mitochondrial Cytosolic Pyruvate', 'M_lac__L_c': 'L Lactate', 'M_nad_c': 'Nicotinamide Adenine Dinucleotide', 'M_nadh_c': 'Nicotinamide Adenine Dinucleotide Reduced', 'M_amp_c': 'AMP', 'M_adp_c': 'ADP', 'M_atp_c': 'ATP', 'M_pi_c': 'Phosphate', 'M_h_c': 'Glycolysis state 19', 'M_h2o_c': 'H2o', 'M__23dpg_c': '2 3 Disphospho D Glycerate', 'M_hb_1o2_c': 'Oxyhemoglobin 1', 'M_hb_c': 'Hemoglobin', 'M_o2_c': 'Mitochondrial Cytosolic O2', 'M_hb_2o2_c': 'Oxyhemoglobin 2', 'M_hb_3o2_c': 'Oxyhemoglobin 3', 'M_hb_4o2_c': 'Oxyhemoglobin 4', 'M_dhb_c': 'Deoxyhemoglobin', 'M_pyk_R0_P_c': 'Pyk phosphoenolpyruvate Complex', 'M_pyk_R0_c': 'Glycolysis state 30', 'M_pyk_R0_A_c': 'Pyk ADP Complex', 'M_pyk_R0_AP_c': 'Pyk ADP phosphoenolpyruvate Complex', 'M_pyk_R1_c': 'Pyk Fdp Complex', 'M_pyk_R1_P_c': 'Pyk phosphoenolpyruvate Fdp Complex', 'M_pyk_R1_A_c': 'Pyk ADP Fdp Complex', 'M_pyk_R1_AP_c': 'Pyk ADP phosphoenolpyruvate Fdp Complex', 'M_pyk_R2_c': 'Pyk Fdp Complex 2', 'M_pyk_R2_P_c': 'Pyk phosphoenolpyruvate Fdp Complex 2', 'M_pyk_R2_A_c': 'Pyk ADP Fdp Complex 2', 'M_pyk_R2_AP_c': 'Pyk ADP phosphoenolpyruvate Fdp Complex 2', 'M_pyk_R3_c': 'Pyk Fdp Complex 3', 'M_pyk_R3_P_c': 'Pyk phosphoenolpyruvate Fdp Complex 3', 'M_pyk_R3_A_c': 'Pyk ADP Fdp Complex 3', 'M_pyk_R3_AP_c': 'Pyk ADP phosphoenolpyruvate Fdp Complex 3', 'M_pyk_R4_c': 'Pyk Fdp Complex 4', 'M_pyk_R4_P_c': 'Pyk phosphoenolpyruvate Fdp Complex 4', 'M_pyk_R4_A_c': 'Pyk ADP Fdp Complex 4', 'M_pyk_R4_AP_c': 'Pyk ADP phosphoenolpyruvate Fdp Complex 4', 'M_pyk_T0_c': 'Glycolysis state 49', 'M_pyk_T1_c': 'Pyk ATP Complex', 'M_pyk_T2_c': 'Pyk ATP Complex 2', 'M_pyk_T3_c': 'Pyk ATP Complex 3', 'M_pyk_T4_c': 'Pyk ATP Complex 4'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_d_glucose': ('M_glc__D_c', 1.24081917841505, 'native SBML value', 'Initial condition for d glucose. Maps to bundled SBML symbol `M_glc__D_c`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_d_glucose_6_phosphate': ('M_g6p_c', 0.0602185259654985, 'native SBML value', 'Initial condition for d glucose 6 phosphate. Maps to bundled SBML symbol `M_g6p_c`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_d_fructose_6_phosphate': ('M_f6p_c', 0.0245635954921956, 'native SBML value', 'Initial condition for d fructose 6 phosphate. Maps to bundled SBML symbol `M_f6p_c`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_d_fructose_1_6_bisphosphate': ('M_fdp_c', 0.00923798760373767, 'native SBML value', 'Initial condition for d fructose 1 6 bisphosphate. Maps to bundled SBML symbol `M_fdp_c`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_dihydroxyacetone_phosphate': ('M_dhap_c', 0.130120897020308, 'native SBML value', 'Initial condition for dihydroxyacetone phosphate. Maps to bundled SBML symbol `M_dhap_c`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'d_glucose': ('M_glc__D_c', 'native SBML value', 'D Glucose. Maps to SBML symbol `M_glc__D_c`.'), 'd_glucose_6_phosphate': ('M_g6p_c', 'native SBML value', 'D Glucose 6 Phosphate. Maps to SBML symbol `M_g6p_c`.'), 'd_fructose_6_phosphate': ('M_f6p_c', 'native SBML value', 'D Fructose 6 Phosphate. Maps to SBML symbol `M_f6p_c`.'), 'd_fructose_1_6_bisphosphate': ('M_fdp_c', 'native SBML value', 'D Fructose 1 6 Bisphosphate. Maps to SBML symbol `M_fdp_c`.'), 'dihydroxyacetone_phosphate': ('M_dhap_c', 'native SBML value', 'Dihydroxyacetone Phosphate. Maps to SBML symbol `M_dhap_c`.')}

    def __init__(self, model_path: str = 'data/MODEL2012150002.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
