# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Winter2017 - Brain Energy Metabolism with PPP."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Winter2017BrainEnergyMetabolismWithPppBiomd0000000627Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Winter2017 - Brain Energy Metabolism with PPP."""

    _SBML_ID = 'BIOMD0000000627'
    _TITLE = 'Winter2017 - Brain Energy Metabolism with PPP'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'species_23': 'brain_energy_state_1', 'species_24': 'co2', 'species_25': 'glucose', 'species_26': 'lactate', 'dHb': 'brain_energy_state_5', 'species_1': 'glucose_2', 'species_2': 'glucose_6_phosphate', 'species_3': 'atp', 'species_7': 'fructose_6_phosphate', 'species_9': 'glyceraldehyde_3_phosphate', 'species_11': 'nadh', 'species_12': 'phosphoenolpyruvate', 'species_15': 'pyruvate', 'species_18': 'lactate_2', 'species_16': 'brain_energy_state_15', 'species_21': 'brain_energy_state_16', 'Na__neurons': 'brain_energy_state_17', 'GLU_neurons': 'brain_energy_state_18', 'ADP_neurons': 'adp', 'AMP_neurons': 'amp', 'Cr_neurons': 'brain_energy_state_21', 'NAD_neurons': 'nad', 'G6L_neurons': 'g6l', 'P6G_neurons': 'p6g', 'Ru5P_neurons': 'ru5p', 'X5P_neurons': 'x5p', 'R5P_neurons': 'r5p', 'S7P_neurons': 's7p', 'E4P_neurons': 'e4p', 'NADPH_neurons': 'nadph', 'NADP_neurons': 'nadp', 'species_4': 'glucose_3', 'species_5': 'atp_2', 'species_6': 'glucose_6_phosphate_2', 'species_8': 'fructose_6_phosphate_2', 'species_10': 'glyceraldehyde_3_phosphate_2', 'species_13': 'nadh_2', 'species_14': 'phosphoenolpyruvate_2', 'species_17': 'pyruvate_2', 'species_19': 'lactate_3', 'species_20': 'brain_energy_state_41', 'species_22': 'brain_energy_state_42', 'Na__astrocytes': 'brain_energy_state_43', 'GLU_astrocytes': 'brain_energy_state_44', 'ADP_astrocytes': 'adp_2', 'AMP_astrocytes': 'amp_2', 'Cr_astrocytes': 'brain_energy_state_47', 'NAD_astrocytes': 'nad_2', 'G6L_astrocytes': 'g6l_2', 'P6G_astrocytes': 'p6g_2', 'Ru5P_astrocytes': 'ru5p_2', 'X5P_astrocytes': 'x5p_2', 'R5P_astrocytes': 'r5p_2', 'S7P_astrocytes': 's7p_2', 'E4P_astrocytes': 'e4p_2', 'NADP_astrocytes': 'nadp_2', 'NADPH_astrocytes': 'nadph_2', 'species_27': 'glucose_4', 'species_28': 'lactate_4', 'GLU_extracellular_space': 'brain_energy_state_60'}
    _OBSERVABLES = ['species_23', 'species_24', 'species_25', 'species_26', 'dHb', 'species_1', 'species_2', 'species_3', 'species_7', 'species_9', 'species_11', 'species_12', 'species_15', 'species_18', 'species_16', 'species_21', 'Na__neurons', 'GLU_neurons', 'ADP_neurons', 'AMP_neurons', 'Cr_neurons', 'NAD_neurons', 'G6L_neurons', 'P6G_neurons', 'Ru5P_neurons', 'X5P_neurons', 'R5P_neurons', 'S7P_neurons', 'E4P_neurons', 'NADPH_neurons', 'NADP_neurons', 'species_4', 'species_5', 'species_6', 'species_8', 'species_10', 'species_13', 'species_14', 'species_17', 'species_19', 'species_20', 'species_22', 'Na__astrocytes', 'GLU_astrocytes', 'ADP_astrocytes', 'AMP_astrocytes', 'Cr_astrocytes', 'NAD_astrocytes', 'G6L_astrocytes', 'P6G_astrocytes', 'Ru5P_astrocytes', 'X5P_astrocytes', 'R5P_astrocytes', 'S7P_astrocytes', 'E4P_astrocytes', 'NADP_astrocytes', 'NADPH_astrocytes', 'species_27', 'species_28', 'GLU_extracellular_space']
    _SPECIES_LABELS = {'species_23': 'Brain Energy state 1', 'species_24': 'CO2', 'species_25': 'glucose', 'species_26': 'lactate', 'dHb': 'Brain Energy state 5', 'species_1': 'glucose 2', 'species_2': 'glucose 6 phosphate', 'species_3': 'ATP', 'species_7': 'fructose 6 phosphate', 'species_9': 'glyceraldehyde 3 phosphate', 'species_11': 'NADH', 'species_12': 'phosphoenolpyruvate', 'species_15': 'pyruvate', 'species_18': 'lactate 2', 'species_16': 'Brain Energy state 15', 'species_21': 'Brain Energy state 16', 'Na__neurons': 'Brain Energy state 17', 'GLU_neurons': 'Brain Energy state 18', 'ADP_neurons': 'ADP', 'AMP_neurons': 'AMP', 'Cr_neurons': 'Brain Energy state 21', 'NAD_neurons': 'NAD', 'G6L_neurons': 'G6l', 'P6G_neurons': 'P6g', 'Ru5P_neurons': 'Ru5p', 'X5P_neurons': 'X5p', 'R5P_neurons': 'R5p', 'S7P_neurons': 'S7p', 'E4P_neurons': 'E4p', 'NADPH_neurons': 'NADPH', 'NADP_neurons': 'NADP', 'species_4': 'glucose 3', 'species_5': 'ATP 2', 'species_6': 'glucose 6 phosphate 2', 'species_8': 'fructose 6 phosphate 2', 'species_10': 'glyceraldehyde 3 phosphate 2', 'species_13': 'NADH 2', 'species_14': 'phosphoenolpyruvate 2', 'species_17': 'pyruvate 2', 'species_19': 'lactate 3', 'species_20': 'Brain Energy state 41', 'species_22': 'Brain Energy state 42', 'Na__astrocytes': 'Brain Energy state 43', 'GLU_astrocytes': 'Brain Energy state 44', 'ADP_astrocytes': 'ADP 2', 'AMP_astrocytes': 'AMP 2', 'Cr_astrocytes': 'Brain Energy state 47', 'NAD_astrocytes': 'NAD 2', 'G6L_astrocytes': 'G6l 2', 'P6G_astrocytes': 'P6g 2', 'Ru5P_astrocytes': 'Ru5p 2', 'X5P_astrocytes': 'X5p 2', 'R5P_astrocytes': 'R5p 2', 'S7P_astrocytes': 'S7p 2', 'E4P_astrocytes': 'E4p 2', 'NADP_astrocytes': 'NADP 2', 'NADPH_astrocytes': 'NADPH 2', 'species_27': 'glucose 4', 'species_28': 'lactate 4', 'GLU_extracellular_space': 'Brain Energy state 60'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_brain_energy_state_1': ('species_23', 0.040323291746644, 'native SBML value', 'Initial condition for brain energy state 1. Maps to bundled SBML symbol `species_23`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_co2': ('species_24', 0.0121467082533562, 'native SBML value', 'Initial condition for co2. Maps to bundled SBML symbol `species_24`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glucose': ('species_25', 0.0253903826849856, 'native SBML value', 'Initial condition for glucose. Maps to bundled SBML symbol `species_25`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_lactate': ('species_26', 0.00188912996259375, 'native SBML value', 'Initial condition for lactate. Maps to bundled SBML symbol `species_26`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_brain_energy_state_5': ('dHb', 0.000262913971209081, 'native SBML value', 'Initial condition for brain energy state 5. Maps to bundled SBML symbol `dHb`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'brain_energy_state_1': ('species_23', 'native SBML value', 'Brain Energy state 1; conservative display label for an abstract SBML state variable. Maps to SBML symbol `species_23`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'co2': ('species_24', 'native SBML value', 'CO2. Maps to SBML symbol `species_24`.'), 'glucose': ('species_25', 'native SBML value', 'glucose. Maps to SBML symbol `species_25`.'), 'lactate': ('species_26', 'native SBML value', 'lactate. Maps to SBML symbol `species_26`.'), 'brain_energy_state_5': ('dHb', 'native SBML value', 'Brain Energy state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `dHb`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/BIOMD0000000627.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
