# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Bae2017 - Mathematical analysis of circadian disruption and metabolic re-entrainment of hepatic gluconeogenesis."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Bae2017MathematicalAnalysisOfCircadianDisruBiomd0000001005Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Bae2017 - Mathematical analysis of circadian disruption and metabolic re-entrainment of hepatic gluconeogenesis."""

    _SBML_ID = 'BIOMD0000001005'
    _TITLE = 'Bae2017 - Mathematical analysis of circadian disruption and metabolic re-entrainment of hepatic gluconeogenesis'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'CRH': 'crh', 'ACTH': 'acth', 'F_HPA': 'metabolic_pathway_state_3', 'F_Cell': 'metabolic_pathway_state_4_cytosolic', 'y1': 'metabolic_pathway_state_5', 'y2': 'metabolic_pathway_state_6', 'y3': 'metabolic_pathway_state_7', 'y4': 'metabolic_pathway_state_8', 'y5': 'metabolic_pathway_state_9', 'y6': 'metabolic_pathway_state_10', 'y7': 'bmal1_clock_complex', 'NAD': 'nad', 'NMN': 'metabolic_pathway_state_13', 'NAM': 'metabolic_pathway_state_14', 'EntF': 'metabolic_pathway_state_15', 'SIRT1': 'metabolic_pathway_state_16', 'y8': 'bmal1_clock_sirt1_complex', 'NAMPT': 'metabolic_pathway_state_18', 'feed2': 'metabolic_pathway_state_19', 'feed3': 'metabolic_pathway_state_20', 'PGC1amRNA': 'metabolic_pathway_state_21', 'PGC1a': 'metabolic_pathway_state_22', 'PGC1aN': 'metabolic_pathway_state_23', 'PGC1aNact': 'metabolic_pathway_state_24', 'FOXO1': 'metabolic_pathway_state_25', 'PckG6p': 'metabolic_pathway_state_26', 'Phpa': 'metabolic_pathway_state_27', 'MR': 'metabolic_pathway_state_28', 'GR_Cell': 'metabolic_pathway_state_29_cytosolic', 'FGR_Cell': 'metabolic_pathway_state_30_cytosolic', 'FMR': 'metabolic_pathway_state_31', 'FMRN': 'metabolic_pathway_state_32', 'FGRN_Cell': 'metabolic_pathway_state_33_cytosolic', 'P': 'metabolic_pathway_state_34', 'mRNAP': 'metabolic_pathway_state_35', 'mRNARP': 'metabolic_pathway_state_36', 'Rp': 'metabolic_pathway_state_37', 'PR': 'metabolic_pathway_state_38', 'GR_HPA': 'metabolic_pathway_state_39', 'FGR_HPA': 'metabolic_pathway_state_40', 'FGRN_HPA': 'metabolic_pathway_state_41'}
    _OBSERVABLES = ['CRH', 'ACTH', 'F_HPA', 'F_Cell', 'y1', 'y2', 'y3', 'y4', 'y5', 'y6', 'y7', 'NAD', 'NMN', 'NAM', 'EntF', 'SIRT1', 'y8', 'NAMPT', 'feed2', 'feed3', 'PGC1amRNA', 'PGC1a', 'PGC1aN', 'PGC1aNact', 'FOXO1', 'PckG6p', 'Phpa', 'MR', 'GR_Cell', 'FGR_Cell', 'FMR', 'FMRN', 'FGRN_Cell', 'P', 'mRNAP', 'mRNARP', 'Rp', 'PR', 'GR_HPA', 'FGR_HPA', 'FGRN_HPA']
    _SPECIES_LABELS = {'CRH': 'CRH', 'ACTH': 'ACTH', 'F_HPA': 'Metabolic Pathway state 3', 'F_Cell': 'Metabolic Pathway state 4 cytosolic', 'y1': 'Metabolic Pathway state 5', 'y2': 'Metabolic Pathway state 6', 'y3': 'Metabolic Pathway state 7', 'y4': 'Metabolic Pathway state 8', 'y5': 'Metabolic Pathway state 9', 'y6': 'Metabolic Pathway state 10', 'y7': 'Bmal1 Clock Complex', 'NAD': 'NAD', 'NMN': 'Metabolic Pathway state 13', 'NAM': 'Metabolic Pathway state 14', 'EntF': 'Metabolic Pathway state 15', 'SIRT1': 'Metabolic Pathway state 16', 'y8': 'Bmal1 Clock Sirt1 Complex', 'NAMPT': 'Metabolic Pathway state 18', 'feed2': 'Metabolic Pathway state 19', 'feed3': 'Metabolic Pathway state 20', 'PGC1amRNA': 'Metabolic Pathway state 21', 'PGC1a': 'Metabolic Pathway state 22', 'PGC1aN': 'Metabolic Pathway state 23', 'PGC1aNact': 'Metabolic Pathway state 24', 'FOXO1': 'Metabolic Pathway state 25', 'PckG6p': 'Metabolic Pathway state 26', 'Phpa': 'Metabolic Pathway state 27', 'MR': 'Metabolic Pathway state 28', 'GR_Cell': 'Metabolic Pathway state 29 cytosolic', 'FGR_Cell': 'Metabolic Pathway state 30 cytosolic', 'FMR': 'Metabolic Pathway state 31', 'FMRN': 'Metabolic Pathway state 32', 'FGRN_Cell': 'Metabolic Pathway state 33 cytosolic', 'P': 'Metabolic Pathway state 34', 'mRNAP': 'Metabolic Pathway state 35', 'mRNARP': 'Metabolic Pathway state 36', 'Rp': 'Metabolic Pathway state 37', 'PR': 'Metabolic Pathway state 38', 'GR_HPA': 'Metabolic Pathway state 39', 'FGR_HPA': 'Metabolic Pathway state 40', 'FGRN_HPA': 'Metabolic Pathway state 41'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_crh': ('CRH', 1.0, 'native SBML value', 'Initial condition for crh. Maps to bundled SBML symbol `CRH`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_acth': ('ACTH', 1.0, 'native SBML value', 'Initial condition for acth. Maps to bundled SBML symbol `ACTH`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_3': ('F_HPA', 1.0, 'native SBML value', 'Initial condition for metabolic pathway state 3. Maps to bundled SBML symbol `F_HPA`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_4_cytosolic': ('F_Cell', 1.0, 'native SBML value', 'Initial condition for metabolic pathway state 4 cytosolic. Maps to bundled SBML symbol `F_Cell`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_5': ('y1', 1.0, 'native SBML value', 'Initial condition for metabolic pathway state 5. Maps to bundled SBML symbol `y1`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'crh': ('CRH', 'native SBML value', 'CRH. Maps to SBML symbol `CRH`.'), 'acth': ('ACTH', 'native SBML value', 'ACTH. Maps to SBML symbol `ACTH`.'), 'metabolic_pathway_state_3': ('F_HPA', 'native SBML value', 'Metabolic Pathway state 3; conservative display label for an abstract SBML state variable. Maps to SBML symbol `F_HPA`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_4_cytosolic': ('F_Cell', 'native SBML value', 'Metabolic Pathway state 4 cytosolic; conservative display label for an abstract SBML state variable. Maps to SBML symbol `F_Cell`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_5': ('y1', 'native SBML value', 'Metabolic Pathway state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `y1`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/BIOMD0000001005.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
