# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for McDougal2017 - Metabolism in ischemic cardiomyocytes."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Mcdougal2017MetabolismInIschemicCardiomyocytBiomd0000000961Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for McDougal2017 - Metabolism in ischemic cardiomyocytes."""

    _SBML_ID = 'BIOMD0000000961'
    _TITLE = 'McDougal2017 - Metabolism in ischemic cardiomyocytes'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'s1': 'h_super_plus_endsuper_sub_i_endsub', 's2': 'h_super_plus_endsuper_sub_o_endsub', 's7': 'oh_super_minus_endsuper_sub_i_endsub', 's8': 'oh_super_minus_endsuper_sub_o_endsub', 's24': 'na_super_plus_endsuper_sub_i_endsub', 's25': 'na_super_plus_endsuper_sub_o_endsub', 's26': 'hco_sub_3_endsub_super_minus_endsuper_sub_i_endsub', 's27': 'hco_sub_3_endsub_super_minus_endsuper_sub_o_endsub', 's28': 'cl_super_minus_endsuper_sub_i_endsub', 's29': 'cl_super_minus_endsuper_sub_o_endsub', 's30': 'atp', 's31': 'adp', 's32': 'p_sub_i_endsub', 's33': 'metabolic_pathway_state_14', 's34': 'metabolic_pathway_state_15', 's35': 'amp', 's36': 'metabolic_pathway_state_17', 's38': 'l_super_minus_endsuper_sub_i_endsub', 's52': 'lactic_acid', 's57': 'glucose_6_phosphate', 's58': 'fructose_6_phosphate', 's59': 'glyceraldehyde_3_phosphate', 's60': 'phosphoenolpyruvate', 's64': 'co_sub_2_endsub', 's66': 'f16bp', 's67': 'metabolic_pathway_state_26', 's68': 'observable_13bpg', 's69': 'observable_3pg', 's70': 'observable_2pg', 's71': 'h_sub_2_endsub_o', 's72': 'g1p', 's73': 'metabolic_pathway_state_32', 's74': 'metabolic_pathway_state_33', 's75': 'metabolic_pathway_state_34', 's76': 'observable_6pgn', 's77': 'glycerol_3_p', 's61': 'pyruvate', 's79': 'g16bp', 's82': 'o_sub_2_e_endsub', 's83': 'metabolic_pathway_state_40', 's84': 'metabolic_pathway_state_41', 's65': 'o_sub_2_endsub'}
    _OBSERVABLES = ['s1', 's2', 's7', 's8', 's24', 's25', 's26', 's27', 's28', 's29', 's30', 's31', 's32', 's33', 's34', 's35', 's36', 's38', 's52', 's57', 's58', 's59', 's60', 's64', 's66', 's67', 's68', 's69', 's70', 's71', 's72', 's73', 's74', 's75', 's76', 's77', 's61', 's79', 's82', 's83', 's84', 's65']
    _SPECIES_LABELS = {'s1': 'H Super Plus Endsuper Sub I Endsub', 's2': 'H Super Plus Endsuper Sub O Endsub', 's7': 'Oh Super Minus Endsuper Sub I Endsub', 's8': 'Oh Super Minus Endsuper Sub O Endsub', 's24': 'Na Super Plus Endsuper Sub I Endsub', 's25': 'Na Super Plus Endsuper Sub O Endsub', 's26': 'Hco Sub 3 Endsub Super Minus Endsuper Sub I Endsub', 's27': 'Hco Sub 3 Endsub Super Minus Endsuper Sub O Endsub', 's28': 'Cl Super Minus Endsuper Sub I Endsub', 's29': 'Cl Super Minus Endsuper Sub O Endsub', 's30': 'ATP', 's31': 'ADP', 's32': 'P Sub I Endsub', 's33': 'Metabolic Pathway state 14', 's34': 'Metabolic Pathway state 15', 's35': 'AMP', 's36': 'Metabolic Pathway state 17', 's38': 'L Super Minus Endsuper Sub I Endsub', 's52': 'Lactic Acid', 's57': 'glucose 6 phosphate', 's58': 'fructose 6 phosphate', 's59': 'glyceraldehyde 3 phosphate', 's60': 'phosphoenolpyruvate', 's64': 'Co Sub 2 Endsub', 's66': 'F16bp', 's67': 'Metabolic Pathway state 26', 's68': '13bpg', 's69': '3pg', 's70': '2pg', 's71': 'H Sub 2 Endsub O', 's72': 'G1p', 's73': 'Metabolic Pathway state 32', 's74': 'Metabolic Pathway state 33', 's75': 'Metabolic Pathway state 34', 's76': '6pgn', 's77': 'Glycerol 3 P', 's61': 'pyruvate', 's79': 'G16bp', 's82': 'O Sub 2 E Endsub', 's83': 'Metabolic Pathway state 40', 's84': 'Metabolic Pathway state 41', 's65': 'O Sub 2 Endsub'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_h_super_plus_endsuper_sub_i_endsub': ('s1', 7.94e-05, 'native SBML value', 'Initial condition for h super plus endsuper sub i endsub. Maps to bundled SBML symbol `s1`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_h_super_plus_endsuper_sub_o_endsub': ('s2', 1e-12, 'native SBML value', 'Initial condition for h super plus endsuper sub o endsub. Maps to bundled SBML symbol `s2`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_oh_super_minus_endsuper_sub_i_endsub': ('s7', 1e-12, 'native SBML value', 'Initial condition for oh super minus endsuper sub i endsub. Maps to bundled SBML symbol `s7`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_oh_super_minus_endsuper_sub_o_endsub': ('s8', 1e-12, 'native SBML value', 'Initial condition for oh super minus endsuper sub o endsub. Maps to bundled SBML symbol `s8`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_na_super_plus_endsuper_sub_i_endsub': ('s24', 5.0, 'native SBML value', 'Initial condition for na super plus endsuper sub i endsub. Maps to bundled SBML symbol `s24`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'h_super_plus_endsuper_sub_i_endsub': ('s1', 'native SBML value', 'H Super Plus Endsuper Sub I Endsub. Maps to SBML symbol `s1`.'), 'h_super_plus_endsuper_sub_o_endsub': ('s2', 'native SBML value', 'H Super Plus Endsuper Sub O Endsub. Maps to SBML symbol `s2`.'), 'oh_super_minus_endsuper_sub_i_endsub': ('s7', 'native SBML value', 'Oh Super Minus Endsuper Sub I Endsub. Maps to SBML symbol `s7`.'), 'oh_super_minus_endsuper_sub_o_endsub': ('s8', 'native SBML value', 'Oh Super Minus Endsuper Sub O Endsub. Maps to SBML symbol `s8`.'), 'na_super_plus_endsuper_sub_i_endsub': ('s24', 'native SBML value', 'Na Super Plus Endsuper Sub I Endsub. Maps to SBML symbol `s24`.')}

    def __init__(self, model_path: str = 'data/BIOMD0000000961.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
