# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Sier2017_E2_combined."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Sier2017E2CombinedModel1711210002Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Sier2017_E2_combined."""

    _SBML_ID = 'MODEL1711210002'
    _TITLE = 'Sier2017_E2_combined'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'Faeces': 'metabolic_pathway_state_1', 'count': 'metabolic_pathway_state_2', 'default_0': 'metabolic_pathway_state_3', 's16': 'metabolic_pathway_state_4', 's18': 'metabolic_pathway_state_5', 's19': 'metabolic_pathway_state_6', 's32': 'metabolic_pathway_state_7', 's33': 'metabolic_pathway_state_8', 's15': 'metabolic_pathway_state_9', 's17': 'metabolic_pathway_state_10', 's20': 'metabolic_pathway_state_11', 's21': 'metabolic_pathway_state_12', 's29': 'metabolic_pathway_state_13', 's1': 'metabolic_pathway_state_14', 's3': 'metabolic_pathway_state_15', 's5': 'metabolic_pathway_state_16', 's8': 'metabolic_pathway_state_17', 's9': 'metabolic_pathway_state_18', 's10': 'metabolic_pathway_state_19', 's11': 'metabolic_pathway_state_20', 's12': 'metabolic_pathway_state_21', 's13': 'metabolic_pathway_state_22', 'E2_Rest_of_body': 'metabolic_pathway_state_23', 'E2_Liver_cells': 'metabolic_pathway_state_24', 'ER_Liver_cells': 'metabolic_pathway_state_25', 'ER_E2_Liver_cells': 'metabolic_pathway_state_26', 'E13S_Liver_cells': 'e13s', 'E217BG_Liver_cells': 'e217bg', 'E2_NSB': 'metabolic_pathway_state_29', 'NSB': 'metabolic_pathway_state_30', '_4OHE2': 'observable_4ohe2', '_2OHE2': 'observable_2ohe2', 'E1': 'metabolic_pathway_state_33', '_4OHE1': 'observable_4ohe1', '_2OHE1': 'observable_2ohe1', 'E2_Brain': 'metabolic_pathway_state_36', 'E2_Gonads_cells': 'metabolic_pathway_state_37', 'ER_Gonads_cells': 'metabolic_pathway_state_38', 'ER_E2_Gonads_cells': 'metabolic_pathway_state_39', 'E2_Skin': 'metabolic_pathway_state_40', 'E2_Muscle': 'metabolic_pathway_state_41', 'E2_Adipose': 'metabolic_pathway_state_42', 'E2_Dose_IV': 'metabolic_pathway_state_43', 'E2_Pancreas': 'metabolic_pathway_state_44', 'E2_Dose_oral': 'metabolic_pathway_state_45', 'E2_Gonads_blood': 'metabolic_pathway_state_46'}
    _OBSERVABLES = ['Faeces', 'count', 'default_0', 's16', 's18', 's19', 's32', 's33', 's15', 's17', 's20', 's21', 's29', 's1', 's3', 's5', 's8', 's9', 's10', 's11', 's12', 's13', 'E2_Rest_of_body', 'E2_Liver_cells', 'ER_Liver_cells', 'ER_E2_Liver_cells', 'E13S_Liver_cells', 'E217BG_Liver_cells', 'E2_NSB', 'NSB', '_4OHE2', '_2OHE2', 'E1', '_4OHE1', '_2OHE1', 'E2_Brain', 'E2_Gonads_cells', 'ER_Gonads_cells', 'ER_E2_Gonads_cells', 'E2_Skin', 'E2_Muscle', 'E2_Adipose', 'E2_Dose_IV', 'E2_Pancreas', 'E2_Dose_oral', 'E2_Gonads_blood']
    _SPECIES_LABELS = {'Faeces': 'Metabolic Pathway state 1', 'count': 'Metabolic Pathway state 2', 'default_0': 'Metabolic Pathway state 3', 's16': 'Metabolic Pathway state 4', 's18': 'Metabolic Pathway state 5', 's19': 'Metabolic Pathway state 6', 's32': 'Metabolic Pathway state 7', 's33': 'Metabolic Pathway state 8', 's15': 'Metabolic Pathway state 9', 's17': 'Metabolic Pathway state 10', 's20': 'Metabolic Pathway state 11', 's21': 'Metabolic Pathway state 12', 's29': 'Metabolic Pathway state 13', 's1': 'Metabolic Pathway state 14', 's3': 'Metabolic Pathway state 15', 's5': 'Metabolic Pathway state 16', 's8': 'Metabolic Pathway state 17', 's9': 'Metabolic Pathway state 18', 's10': 'Metabolic Pathway state 19', 's11': 'Metabolic Pathway state 20', 's12': 'Metabolic Pathway state 21', 's13': 'Metabolic Pathway state 22', 'E2_Rest_of_body': 'Metabolic Pathway state 23', 'E2_Liver_cells': 'Metabolic Pathway state 24', 'ER_Liver_cells': 'Metabolic Pathway state 25', 'ER_E2_Liver_cells': 'Metabolic Pathway state 26', 'E13S_Liver_cells': 'E13s', 'E217BG_Liver_cells': 'E217bg', 'E2_NSB': 'Metabolic Pathway state 29', 'NSB': 'Metabolic Pathway state 30', '_4OHE2': '4ohe2', '_2OHE2': '2ohe2', 'E1': 'Metabolic Pathway state 33', '_4OHE1': '4ohe1', '_2OHE1': '2ohe1', 'E2_Brain': 'Metabolic Pathway state 36', 'E2_Gonads_cells': 'Metabolic Pathway state 37', 'ER_Gonads_cells': 'Metabolic Pathway state 38', 'ER_E2_Gonads_cells': 'Metabolic Pathway state 39', 'E2_Skin': 'Metabolic Pathway state 40', 'E2_Muscle': 'Metabolic Pathway state 41', 'E2_Adipose': 'Metabolic Pathway state 42', 'E2_Dose_IV': 'Metabolic Pathway state 43', 'E2_Pancreas': 'Metabolic Pathway state 44', 'E2_Dose_oral': 'Metabolic Pathway state 45', 'E2_Gonads_blood': 'Metabolic Pathway state 46'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_metabolic_pathway_state_1': ('Faeces', 1.0, 'native SBML value', 'Initial condition for metabolic pathway state 1. Maps to bundled SBML symbol `Faeces`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_2': ('count', 3001.00000000002, 'native SBML value', 'Initial condition for metabolic pathway state 2. Maps to bundled SBML symbol `count`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_3': ('default_0', -2999.00000000002, 'native SBML value', 'Initial condition for metabolic pathway state 3. Maps to bundled SBML symbol `default_0`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_4': ('s16', 0.0209437464725829, 'native SBML value', 'Initial condition for metabolic pathway state 4. Maps to bundled SBML symbol `s16`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_5': ('s18', 39.4491907670147, 'native SBML value', 'Initial condition for metabolic pathway state 5. Maps to bundled SBML symbol `s18`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'metabolic_pathway_state_1': ('Faeces', 'native SBML value', 'Metabolic Pathway state 1; conservative display label for an abstract SBML state variable. Maps to SBML symbol `Faeces`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_2': ('count', 'native SBML value', 'Metabolic Pathway state 2; conservative display label for an abstract SBML state variable. Maps to SBML symbol `count`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_3': ('default_0', 'native SBML value', 'Metabolic Pathway state 3; conservative display label for an abstract SBML state variable. Maps to SBML symbol `default_0`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_4': ('s16', 'native SBML value', 'Metabolic Pathway state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `s16`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_5': ('s18', 'native SBML value', 'Metabolic Pathway state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `s18`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/MODEL1711210002.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
