# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Mulquiney1999_BPG_metabolism."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Mulquiney1999BpgMetabolismModel5950552398Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Mulquiney1999_BPG_metabolism."""

    _SBML_ID = 'MODEL5950552398'
    _TITLE = 'Mulquiney1999_BPG_metabolism'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'MgATP': 'metabolic_pathway_state_1', 'Glc6P': 'metabolic_pathway_state_2', 'MgADP': 'metabolic_pathway_state_3', 'B23PG': 'metabolic_pathway_state_4', 'Glc16P2': 'metabolic_pathway_state_5', 'GSH': 'glutathione', 'Fru6P': 'fructose_6_phosphate', 'Fru16P2': 'metabolic_pathway_state_8', 'ATP': 'atp', 'Mg': 'metabolic_pathway_state_10', 'AMP': 'amp', 'Phos': 'metabolic_pathway_state_12', 'GrnP': 'metabolic_pathway_state_13', 'GraP': 'metabolic_pathway_state_14', 'MgB23PG': 'metabolic_pathway_state_15', 'NAD': 'nad', 'B13PG': 'metabolic_pathway_state_17', 'NADH': 'nadh', 'P3GA': 'metabolic_pathway_state_19', 'P2GA': 'metabolic_pathway_state_20', 'PEP': 'phosphoenolpyruvate', 'Pyr': 'pyruvate', 'Lac': 'lactate', 'NADPH': 'nadph', 'NADP': 'nadp', 'BPGSP': 'metabolic_pathway_state_26', 'BPGSPB13PG': 'metabolic_pathway_state_27', 'BPGSPP': 'metabolic_pathway_state_28', 'BPGSPPP3GA': 'metabolic_pathway_state_29', 'BPGSPPP2GA': 'metabolic_pathway_state_30', 'BPGSPB23PG': 'metabolic_pathway_state_31', 'BPGSPPPhos': 'metabolic_pathway_state_32', 'P6GL': 'metabolic_pathway_state_33', 'P6G': 'metabolic_pathway_state_34', 'Ru5P': 'metabolic_pathway_state_35', 'GSSG': 'oxidized_glutathione', 'Xu5P': 'metabolic_pathway_state_37', 'Rib5P': 'metabolic_pathway_state_38', 'TK': 'metabolic_pathway_state_39', 'TKXu5P': 'metabolic_pathway_state_40', 'TKG': 'metabolic_pathway_state_41', 'TKGRib5P': 'metabolic_pathway_state_42', 'Sed7P': 'metabolic_pathway_state_43', 'Ery4P': 'metabolic_pathway_state_44', 'TKGEry4P': 'metabolic_pathway_state_45', 'ADP': 'adp', 'MgB13PG': 'metabolic_pathway_state_47', 'MgFru16P2': 'metabolic_pathway_state_48', 'MgGlc16P2': 'metabolic_pathway_state_49', 'MgPhos': 'metabolic_pathway_state_50', 'Hb': 'metabolic_pathway_state_51', 'HbMgATP': 'metabolic_pathway_state_52', 'HbATP': 'metabolic_pathway_state_53', 'HbADP': 'metabolic_pathway_state_54', 'HbB23PG': 'metabolic_pathway_state_55', 'HbB13PG': 'metabolic_pathway_state_56'}
    _OBSERVABLES = ['MgATP', 'Glc6P', 'MgADP', 'B23PG', 'Glc16P2', 'GSH', 'Fru6P', 'Fru16P2', 'ATP', 'Mg', 'AMP', 'Phos', 'GrnP', 'GraP', 'MgB23PG', 'NAD', 'B13PG', 'NADH', 'P3GA', 'P2GA', 'PEP', 'Pyr', 'Lac', 'NADPH', 'NADP', 'BPGSP', 'BPGSPB13PG', 'BPGSPP', 'BPGSPPP3GA', 'BPGSPPP2GA', 'BPGSPB23PG', 'BPGSPPPhos', 'P6GL', 'P6G', 'Ru5P', 'GSSG', 'Xu5P', 'Rib5P', 'TK', 'TKXu5P', 'TKG', 'TKGRib5P', 'Sed7P', 'Ery4P', 'TKGEry4P', 'ADP', 'MgB13PG', 'MgFru16P2', 'MgGlc16P2', 'MgPhos', 'Hb', 'HbMgATP', 'HbATP', 'HbADP', 'HbB23PG', 'HbB13PG']
    _SPECIES_LABELS = {'MgATP': 'Metabolic Pathway state 1', 'Glc6P': 'Metabolic Pathway state 2', 'MgADP': 'Metabolic Pathway state 3', 'B23PG': 'Metabolic Pathway state 4', 'Glc16P2': 'Metabolic Pathway state 5', 'GSH': 'Glutathione', 'Fru6P': 'Fructose 6 Phosphate', 'Fru16P2': 'Metabolic Pathway state 8', 'ATP': 'ATP', 'Mg': 'Metabolic Pathway state 10', 'AMP': 'AMP', 'Phos': 'Metabolic Pathway state 12', 'GrnP': 'Metabolic Pathway state 13', 'GraP': 'Metabolic Pathway state 14', 'MgB23PG': 'Metabolic Pathway state 15', 'NAD': 'NAD', 'B13PG': 'Metabolic Pathway state 17', 'NADH': 'NADH', 'P3GA': 'Metabolic Pathway state 19', 'P2GA': 'Metabolic Pathway state 20', 'PEP': 'Phosphoenolpyruvate', 'Pyr': 'Pyruvate', 'Lac': 'Lactate', 'NADPH': 'NADPH', 'NADP': 'NADP', 'BPGSP': 'Metabolic Pathway state 26', 'BPGSPB13PG': 'Metabolic Pathway state 27', 'BPGSPP': 'Metabolic Pathway state 28', 'BPGSPPP3GA': 'Metabolic Pathway state 29', 'BPGSPPP2GA': 'Metabolic Pathway state 30', 'BPGSPB23PG': 'Metabolic Pathway state 31', 'BPGSPPPhos': 'Metabolic Pathway state 32', 'P6GL': 'Metabolic Pathway state 33', 'P6G': 'Metabolic Pathway state 34', 'Ru5P': 'Metabolic Pathway state 35', 'GSSG': 'Oxidized Glutathione', 'Xu5P': 'Metabolic Pathway state 37', 'Rib5P': 'Metabolic Pathway state 38', 'TK': 'Metabolic Pathway state 39', 'TKXu5P': 'Metabolic Pathway state 40', 'TKG': 'Metabolic Pathway state 41', 'TKGRib5P': 'Metabolic Pathway state 42', 'Sed7P': 'Metabolic Pathway state 43', 'Ery4P': 'Metabolic Pathway state 44', 'TKGEry4P': 'Metabolic Pathway state 45', 'ADP': 'ADP', 'MgB13PG': 'Metabolic Pathway state 47', 'MgFru16P2': 'Metabolic Pathway state 48', 'MgGlc16P2': 'Metabolic Pathway state 49', 'MgPhos': 'Metabolic Pathway state 50', 'Hb': 'Metabolic Pathway state 51', 'HbMgATP': 'Metabolic Pathway state 52', 'HbATP': 'Metabolic Pathway state 53', 'HbADP': 'Metabolic Pathway state 54', 'HbB23PG': 'Metabolic Pathway state 55', 'HbB13PG': 'Metabolic Pathway state 56'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_metabolic_pathway_state_1': ('MgATP', 0.0, 'native SBML value', 'Initial condition for metabolic pathway state 1. Maps to bundled SBML symbol `MgATP`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_2': ('Glc6P', 4e-05, 'native SBML value', 'Initial condition for metabolic pathway state 2. Maps to bundled SBML symbol `Glc6P`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_3': ('MgADP', 0.0, 'native SBML value', 'Initial condition for metabolic pathway state 3. Maps to bundled SBML symbol `MgADP`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_4': ('B23PG', 0.0067, 'native SBML value', 'Initial condition for metabolic pathway state 4. Maps to bundled SBML symbol `B23PG`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_5': ('Glc16P2', 0.000122, 'native SBML value', 'Initial condition for metabolic pathway state 5. Maps to bundled SBML symbol `Glc16P2`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'metabolic_pathway_state_1': ('MgATP', 'native SBML value', 'Metabolic Pathway state 1; conservative display label for an abstract SBML state variable. Maps to SBML symbol `MgATP`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_2': ('Glc6P', 'native SBML value', 'Metabolic Pathway state 2; conservative display label for an abstract SBML state variable. Maps to SBML symbol `Glc6P`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_3': ('MgADP', 'native SBML value', 'Metabolic Pathway state 3; conservative display label for an abstract SBML state variable. Maps to SBML symbol `MgADP`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_4': ('B23PG', 'native SBML value', 'Metabolic Pathway state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `B23PG`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_5': ('Glc16P2', 'native SBML value', 'Metabolic Pathway state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `Glc16P2`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/MODEL5950552398.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
