# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for PetelenzKuehn_osmoadaptation_gpd1D."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class PetelenzkuehnOsmoadaptationGpd1dBiomd0000000610Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for PetelenzKuehn_osmoadaptation_gpd1D."""

    _SBML_ID = 'BIOMD0000000610'
    _TITLE = 'PetelenzKuehn_osmoadaptation_gpd1D'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'glycerol_i': 'metabolic_pathway_state_1', 'cin': 'metabolic_pathway_state_2', 'glucose_i': 'metabolic_pathway_state_3', 'G6P': 'glucose_6_phosphate', 'trehalose': 'metabolic_pathway_state_5', 'F16DP': 'metabolic_pathway_state_6', 'F26DP': 'metabolic_pathway_state_7', 'trioseP': 'metabolic_pathway_state_8', 'Gpd1': 'metabolic_pathway_state_9', 'pyruvate': 'metabolic_pathway_state_10', 'acetate_i': 'metabolic_pathway_state_11', 'ethanol_i': 'metabolic_pathway_state_12', 'Hog1': 'metabolic_pathway_state_13', 'Hog1PP': 'metabolic_pathway_state_14', 'Pfk2627a': 'metabolic_pathway_state_15', 'Pfk2627i': 'metabolic_pathway_state_16', 'AOG': 'metabolic_pathway_state_17', 'gpd1mRNA': 'metabolic_pathway_state_18', 'stl1mRNA': 'metabolic_pathway_state_19', 'Stl1': 'metabolic_pathway_state_20', 'AOGi': 'metabolic_pathway_state_21', 'Fps1r': 'metabolic_pathway_state_22', 'biomass': 'metabolic_pathway_state_23', 'cellvol': 'metabolic_pathway_state_24', 'glycerol_e': 'metabolic_pathway_state_25', 'glucose_e': 'metabolic_pathway_state_26', 'acetate_e': 'metabolic_pathway_state_27', 'ethanol_e': 'metabolic_pathway_state_28', 'trehalose_e': 'metabolic_pathway_state_29'}
    _OBSERVABLES = ['glycerol_i', 'cin', 'glucose_i', 'G6P', 'trehalose', 'F16DP', 'F26DP', 'trioseP', 'Gpd1', 'pyruvate', 'acetate_i', 'ethanol_i', 'Hog1', 'Hog1PP', 'Pfk2627a', 'Pfk2627i', 'AOG', 'gpd1mRNA', 'stl1mRNA', 'Stl1', 'AOGi', 'Fps1r', 'biomass', 'cellvol', 'glycerol_e', 'glucose_e', 'acetate_e', 'ethanol_e', 'trehalose_e']
    _SPECIES_LABELS = {'glycerol_i': 'Metabolic Pathway state 1', 'cin': 'Metabolic Pathway state 2', 'glucose_i': 'Metabolic Pathway state 3', 'G6P': 'Glucose 6 Phosphate', 'trehalose': 'Metabolic Pathway state 5', 'F16DP': 'Metabolic Pathway state 6', 'F26DP': 'Metabolic Pathway state 7', 'trioseP': 'Metabolic Pathway state 8', 'Gpd1': 'Metabolic Pathway state 9', 'pyruvate': 'Metabolic Pathway state 10', 'acetate_i': 'Metabolic Pathway state 11', 'ethanol_i': 'Metabolic Pathway state 12', 'Hog1': 'Metabolic Pathway state 13', 'Hog1PP': 'Metabolic Pathway state 14', 'Pfk2627a': 'Metabolic Pathway state 15', 'Pfk2627i': 'Metabolic Pathway state 16', 'AOG': 'Metabolic Pathway state 17', 'gpd1mRNA': 'Metabolic Pathway state 18', 'stl1mRNA': 'Metabolic Pathway state 19', 'Stl1': 'Metabolic Pathway state 20', 'AOGi': 'Metabolic Pathway state 21', 'Fps1r': 'Metabolic Pathway state 22', 'biomass': 'Metabolic Pathway state 23', 'cellvol': 'Metabolic Pathway state 24', 'glycerol_e': 'Metabolic Pathway state 25', 'glucose_e': 'Metabolic Pathway state 26', 'acetate_e': 'Metabolic Pathway state 27', 'ethanol_e': 'Metabolic Pathway state 28', 'trehalose_e': 'Metabolic Pathway state 29'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_metabolic_pathway_state_1': ('glycerol_i', 0.112096, 'native SBML value', 'Initial condition for metabolic pathway state 1. Maps to bundled SBML symbol `glycerol_i`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_2': ('cin', 0.651922, 'native SBML value', 'Initial condition for metabolic pathway state 2. Maps to bundled SBML symbol `cin`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_3': ('glucose_i', 2.77983, 'native SBML value', 'Initial condition for metabolic pathway state 3. Maps to bundled SBML symbol `glucose_i`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glucose_6_phosphate': ('G6P', 1.37587, 'native SBML value', 'Initial condition for glucose 6 phosphate. Maps to bundled SBML symbol `G6P`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_5': ('trehalose', 0.00309562, 'native SBML value', 'Initial condition for metabolic pathway state 5. Maps to bundled SBML symbol `trehalose`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'metabolic_pathway_state_1': ('glycerol_i', 'native SBML value', 'Metabolic Pathway state 1; conservative display label for an abstract SBML state variable. Maps to SBML symbol `glycerol_i`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_2': ('cin', 'native SBML value', 'Metabolic Pathway state 2; conservative display label for an abstract SBML state variable. Maps to SBML symbol `cin`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_3': ('glucose_i', 'native SBML value', 'Metabolic Pathway state 3; conservative display label for an abstract SBML state variable. Maps to SBML symbol `glucose_i`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glucose_6_phosphate': ('G6P', 'native SBML value', 'Glucose 6 Phosphate. Maps to SBML symbol `G6P`.'), 'metabolic_pathway_state_5': ('trehalose', 'native SBML value', 'Metabolic Pathway state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `trehalose`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/BIOMD0000000610.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
