# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for ODea2007_IkappaB."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Odea2007IkappabBiomd0000000147Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for ODea2007_IkappaB."""

    _SBML_ID = 'BIOMD0000000147'
    _TITLE = 'ODea2007_IkappaB'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'IkBa_mRNA': 'metabolic_pathway_state_1', 'IkBa_cytoplasm': 'metabolic_pathway_state_2', 'IkBa_nucleus': 'metabolic_pathway_state_3', 'IkBaIKK': 'metabolic_pathway_state_4', 'IkBaNFkB_cytoplasm': 'metabolic_pathway_state_5', 'IkBaNFkB_nucleus': 'metabolic_pathway_state_6', 'IkBaIKKNFkB': 'metabolic_pathway_state_7', 'NFkB_cytoplasm': 'metabolic_pathway_state_8', 'IKK': 'metabolic_pathway_state_9', 'NFkB_nucleus': 'metabolic_pathway_state_10', 'IkBbIKK': 'metabolic_pathway_state_11', 'IkBbIKKNFkB': 'metabolic_pathway_state_12', 'IkBbNFkB_nucleus': 'metabolic_pathway_state_13', 'IkBbNFkB_cytoplasm': 'metabolic_pathway_state_14', 'IkBb_nucleus': 'metabolic_pathway_state_15', 'IkBb_cytoplasm': 'metabolic_pathway_state_16', 'IkBb_mRNA': 'metabolic_pathway_state_17', 'IkBe_mRNA': 'metabolic_pathway_state_18', 'IkBe_cytoplasm': 'metabolic_pathway_state_19', 'IkBe_nucleus': 'metabolic_pathway_state_20', 'IkBeNFkB_cytoplasm': 'metabolic_pathway_state_21', 'IkBeNFkB_nucleus': 'metabolic_pathway_state_22', 'IkBeIKKNFkB': 'metabolic_pathway_state_23', 'IkBeIKK': 'metabolic_pathway_state_24'}
    _OBSERVABLES = ['IkBa_mRNA', 'IkBa_cytoplasm', 'IkBa_nucleus', 'IkBaIKK', 'IkBaNFkB_cytoplasm', 'IkBaNFkB_nucleus', 'IkBaIKKNFkB', 'NFkB_cytoplasm', 'IKK', 'NFkB_nucleus', 'IkBbIKK', 'IkBbIKKNFkB', 'IkBbNFkB_nucleus', 'IkBbNFkB_cytoplasm', 'IkBb_nucleus', 'IkBb_cytoplasm', 'IkBb_mRNA', 'IkBe_mRNA', 'IkBe_cytoplasm', 'IkBe_nucleus', 'IkBeNFkB_cytoplasm', 'IkBeNFkB_nucleus', 'IkBeIKKNFkB', 'IkBeIKK']
    _SPECIES_LABELS = {'IkBa_mRNA': 'Metabolic Pathway state 1', 'IkBa_cytoplasm': 'Metabolic Pathway state 2', 'IkBa_nucleus': 'Metabolic Pathway state 3', 'IkBaIKK': 'Metabolic Pathway state 4', 'IkBaNFkB_cytoplasm': 'Metabolic Pathway state 5', 'IkBaNFkB_nucleus': 'Metabolic Pathway state 6', 'IkBaIKKNFkB': 'Metabolic Pathway state 7', 'NFkB_cytoplasm': 'Metabolic Pathway state 8', 'IKK': 'Metabolic Pathway state 9', 'NFkB_nucleus': 'Metabolic Pathway state 10', 'IkBbIKK': 'Metabolic Pathway state 11', 'IkBbIKKNFkB': 'Metabolic Pathway state 12', 'IkBbNFkB_nucleus': 'Metabolic Pathway state 13', 'IkBbNFkB_cytoplasm': 'Metabolic Pathway state 14', 'IkBb_nucleus': 'Metabolic Pathway state 15', 'IkBb_cytoplasm': 'Metabolic Pathway state 16', 'IkBb_mRNA': 'Metabolic Pathway state 17', 'IkBe_mRNA': 'Metabolic Pathway state 18', 'IkBe_cytoplasm': 'Metabolic Pathway state 19', 'IkBe_nucleus': 'Metabolic Pathway state 20', 'IkBeNFkB_cytoplasm': 'Metabolic Pathway state 21', 'IkBeNFkB_nucleus': 'Metabolic Pathway state 22', 'IkBeIKKNFkB': 'Metabolic Pathway state 23', 'IkBeIKK': 'Metabolic Pathway state 24'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_metabolic_pathway_state_1': ('IkBa_mRNA', 0.0, 'native SBML value', 'Initial condition for metabolic pathway state 1. Maps to bundled SBML symbol `IkBa_mRNA`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_2': ('IkBa_cytoplasm', 0.0, 'native SBML value', 'Initial condition for metabolic pathway state 2. Maps to bundled SBML symbol `IkBa_cytoplasm`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_3': ('IkBa_nucleus', 0.0, 'native SBML value', 'Initial condition for metabolic pathway state 3. Maps to bundled SBML symbol `IkBa_nucleus`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_4': ('IkBaIKK', 0.0, 'native SBML value', 'Initial condition for metabolic pathway state 4. Maps to bundled SBML symbol `IkBaIKK`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_5': ('IkBaNFkB_cytoplasm', 0.06, 'native SBML value', 'Initial condition for metabolic pathway state 5. Maps to bundled SBML symbol `IkBaNFkB_cytoplasm`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'metabolic_pathway_state_1': ('IkBa_mRNA', 'native SBML value', 'Metabolic Pathway state 1; conservative display label for an abstract SBML state variable. Maps to SBML symbol `IkBa_mRNA`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_2': ('IkBa_cytoplasm', 'native SBML value', 'Metabolic Pathway state 2; conservative display label for an abstract SBML state variable. Maps to SBML symbol `IkBa_cytoplasm`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_3': ('IkBa_nucleus', 'native SBML value', 'Metabolic Pathway state 3; conservative display label for an abstract SBML state variable. Maps to SBML symbol `IkBa_nucleus`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_4': ('IkBaIKK', 'native SBML value', 'Metabolic Pathway state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `IkBaIKK`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'metabolic_pathway_state_5': ('IkBaNFkB_cytoplasm', 'native SBML value', 'Metabolic Pathway state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `IkBaNFkB_cytoplasm`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/BIOMD0000000147.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
