# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Aubert2005 - Interaction between astrocytes and neurons on energy metabolism."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Aubert2005InteractionBetweenAstrocytesAndNeModel1411210000Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Aubert2005 - Interaction between astrocytes and neurons on energy metabolism."""

    _SBML_ID = 'MODEL1411210000'
    _TITLE = 'Aubert2005 - Interaction between astrocytes and neurons on energy metabolism'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'ADPn': 'neuronal_adp', 'AMPn': 'neuronal_amp', 'ADPg': 'brain_energy_state_3', 'AMPg': 'brain_energy_state_4', 'rcn': 'brain_energy_state_5', 'rcg': 'brain_energy_state_6', 'rce': 'brain_energy_state_7', 'reg': 'brain_energy_state_8', 'ren': 'brain_energy_state_9', 'un': 'brain_energy_state_10', 'ug': 'brain_energy_state_11', 'BOLD': 'brain_energy_state_12', 'VnLeak_Na': 'brain_energy_state_13', 'VgLeak_Na': 'brain_energy_state_14', 'VnPump': 'brain_energy_state_15', 'VgPump': 'brain_energy_state_16', 'VnStim_t': 'brain_energy_state_17', 'VgStim_t': 'brain_energy_state_18', 'VenGLC': 'brain_energy_state_19', 'VegGLC': 'brain_energy_state_20', 'VcgGLC': 'brain_energy_state_21', 'VceGLC': 'brain_energy_state_22', 'VnHK_PFK': 'brain_energy_state_23', 'VgHK_PFK': 'brain_energy_state_24', 'VnPGK': 'brain_energy_state_25', 'VgPGK': 'brain_energy_state_26', 'VnPK': 'brain_energy_state_27', 'VgPK': 'brain_energy_state_28', 'VnLDH': 'brain_energy_state_29', 'VgLDH': 'brain_energy_state_30', 'VneLAC': 'brain_energy_state_31', 'VgeLAC': 'brain_energy_state_32', 'VgcLAC': 'brain_energy_state_33', 'VecLAC': 'brain_energy_state_34', 'VnMito': 'brain_energy_state_35', 'VgMito': 'brain_energy_state_36', 'VnCK': 'brain_energy_state_37', 'VgCK': 'brain_energy_state_38', 'VcnO2m': 'brain_energy_state_39', 'VcgO2m': 'brain_energy_state_40', 'Fin_t': 'brain_energy_state_41', 'VcO2': 'brain_energy_state_42', 'VcGLC': 'brain_energy_state_43', 'VcLAC': 'brain_energy_state_44', 'Fout_t': 'brain_energy_state_45', 'O2C': 'o2c', 'dAMP_dATPg': 'brain_energy_state_47', 'dAMP_dATPn': 'brain_energy_state_48', 'ATPn': 'neuronal_atp', 'Nan': 'brain_energy_state_50', 'GLCn': 'neuronal_glucose', 'GAPn': 'neuronal_glyceraldehyde_3_phosphate', 'PEPn': 'neuronal_phosphoenolpyruvate', 'PYRn': 'neuronal_pyruvate', 'LACn': 'neuronal_lactate', 'NADHn': 'neuronal_nadh', 'PCrn': 'brain_energy_state_57', 'O2n': 'neuronal_o2', 'ATPg': 'brain_energy_state_59', 'Nag': 'brain_energy_state_60', 'GLCg': 'brain_energy_state_61', 'GAPg': 'brain_energy_state_62', 'PEPg': 'brain_energy_state_63', 'PYRg': 'brain_energy_state_64', 'LACg': 'brain_energy_state_65', 'NADHg': 'brain_energy_state_66', 'PCrg': 'brain_energy_state_67', 'O2g': 'brain_energy_state_68', 'GLCe': 'extracellular_glucose', 'LACe': 'extracellular_lactate', 'dHb': 'brain_energy_state_71', 'O2c': 'cytosolic_o2', 'GLCc': 'cytosolic_glucose', 'LACc': 'cytosolic_lactate', 'Vv': 'brain_energy_state_75'}
    _OBSERVABLES = ['ADPn', 'AMPn', 'ADPg', 'AMPg', 'rcn', 'rcg', 'rce', 'reg', 'ren', 'un', 'ug', 'BOLD', 'VnLeak_Na', 'VgLeak_Na', 'VnPump', 'VgPump', 'VnStim_t', 'VgStim_t', 'VenGLC', 'VegGLC', 'VcgGLC', 'VceGLC', 'VnHK_PFK', 'VgHK_PFK', 'VnPGK', 'VgPGK', 'VnPK', 'VgPK', 'VnLDH', 'VgLDH', 'VneLAC', 'VgeLAC', 'VgcLAC', 'VecLAC', 'VnMito', 'VgMito', 'VnCK', 'VgCK', 'VcnO2m', 'VcgO2m', 'Fin_t', 'VcO2', 'VcGLC', 'VcLAC', 'Fout_t', 'O2C', 'dAMP_dATPg', 'dAMP_dATPn', 'ATPn', 'Nan', 'GLCn', 'GAPn', 'PEPn', 'PYRn', 'LACn', 'NADHn', 'PCrn', 'O2n', 'ATPg', 'Nag', 'GLCg', 'GAPg', 'PEPg', 'PYRg', 'LACg', 'NADHg', 'PCrg', 'O2g', 'GLCe', 'LACe', 'dHb', 'O2c', 'GLCc', 'LACc', 'Vv']
    _SPECIES_LABELS = {'ADPn': 'Neuronal ADP', 'AMPn': 'Neuronal AMP', 'ADPg': 'Brain Energy state 3', 'AMPg': 'Brain Energy state 4', 'rcn': 'Brain Energy state 5', 'rcg': 'Brain Energy state 6', 'rce': 'Brain Energy state 7', 'reg': 'Brain Energy state 8', 'ren': 'Brain Energy state 9', 'un': 'Brain Energy state 10', 'ug': 'Brain Energy state 11', 'BOLD': 'Brain Energy state 12', 'VnLeak_Na': 'Brain Energy state 13', 'VgLeak_Na': 'Brain Energy state 14', 'VnPump': 'Brain Energy state 15', 'VgPump': 'Brain Energy state 16', 'VnStim_t': 'Brain Energy state 17', 'VgStim_t': 'Brain Energy state 18', 'VenGLC': 'Brain Energy state 19', 'VegGLC': 'Brain Energy state 20', 'VcgGLC': 'Brain Energy state 21', 'VceGLC': 'Brain Energy state 22', 'VnHK_PFK': 'Brain Energy state 23', 'VgHK_PFK': 'Brain Energy state 24', 'VnPGK': 'Brain Energy state 25', 'VgPGK': 'Brain Energy state 26', 'VnPK': 'Brain Energy state 27', 'VgPK': 'Brain Energy state 28', 'VnLDH': 'Brain Energy state 29', 'VgLDH': 'Brain Energy state 30', 'VneLAC': 'Brain Energy state 31', 'VgeLAC': 'Brain Energy state 32', 'VgcLAC': 'Brain Energy state 33', 'VecLAC': 'Brain Energy state 34', 'VnMito': 'Brain Energy state 35', 'VgMito': 'Brain Energy state 36', 'VnCK': 'Brain Energy state 37', 'VgCK': 'Brain Energy state 38', 'VcnO2m': 'Brain Energy state 39', 'VcgO2m': 'Brain Energy state 40', 'Fin_t': 'Brain Energy state 41', 'VcO2': 'Brain Energy state 42', 'VcGLC': 'Brain Energy state 43', 'VcLAC': 'Brain Energy state 44', 'Fout_t': 'Brain Energy state 45', 'O2C': 'O2c', 'dAMP_dATPg': 'Brain Energy state 47', 'dAMP_dATPn': 'Brain Energy state 48', 'ATPn': 'Neuronal ATP', 'Nan': 'Brain Energy state 50', 'GLCn': 'Neuronal Glucose', 'GAPn': 'Neuronal Glyceraldehyde 3 Phosphate', 'PEPn': 'Neuronal Phosphoenolpyruvate', 'PYRn': 'Neuronal Pyruvate', 'LACn': 'Neuronal Lactate', 'NADHn': 'Neuronal NADH', 'PCrn': 'Brain Energy state 57', 'O2n': 'Neuronal O2', 'ATPg': 'Brain Energy state 59', 'Nag': 'Brain Energy state 60', 'GLCg': 'Brain Energy state 61', 'GAPg': 'Brain Energy state 62', 'PEPg': 'Brain Energy state 63', 'PYRg': 'Brain Energy state 64', 'LACg': 'Brain Energy state 65', 'NADHg': 'Brain Energy state 66', 'PCrg': 'Brain Energy state 67', 'O2g': 'Brain Energy state 68', 'GLCe': 'Extracellular Glucose', 'LACe': 'Extracellular Lactate', 'dHb': 'Brain Energy state 71', 'O2c': 'Cytosolic O2', 'GLCc': 'Cytosolic Glucose', 'LACc': 'Cytosolic Lactate', 'Vv': 'Brain Energy state 75'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_neuronal_adp': ('ADPn', 0.0119296850858459, 'native SBML value', 'Initial condition for neuronal adp. Maps to bundled SBML symbol `ADPn`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_neuronal_amp': ('AMPn', 7.03149141538795e-05, 'native SBML value', 'Initial condition for neuronal amp. Maps to bundled SBML symbol `AMPn`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_brain_energy_state_3': ('ADPg', 0.0119296850858464, 'native SBML value', 'Initial condition for brain energy state 3. Maps to bundled SBML symbol `ADPg`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_brain_energy_state_4': ('AMPg', 7.03149141538795e-05, 'native SBML value', 'Initial condition for brain energy state 4. Maps to bundled SBML symbol `AMPg`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_brain_energy_state_5': ('rcn', 0.0122222222222222, 'native SBML value', 'Initial condition for brain energy state 5. Maps to bundled SBML symbol `rcn`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'neuronal_adp': ('ADPn', 'native SBML value', 'Neuronal ADP. Maps to SBML symbol `ADPn`.'), 'neuronal_amp': ('AMPn', 'native SBML value', 'Neuronal AMP. Maps to SBML symbol `AMPn`.'), 'brain_energy_state_3': ('ADPg', 'native SBML value', 'Brain Energy state 3; conservative display label for an abstract SBML state variable. Maps to SBML symbol `ADPg`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'brain_energy_state_4': ('AMPg', 'native SBML value', 'Brain Energy state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `AMPg`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'brain_energy_state_5': ('rcn', 'native SBML value', 'Brain Energy state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `rcn`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/MODEL1411210000.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
