# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Furr2005 - whole-body vitamin A metabolism in humans."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Furr2005WholeBodyVitaminAMetabolismInHumaModel2405200001Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Furr2005 - whole-body vitamin A metabolism in humans."""

    _SBML_ID = 'MODEL2405200001'
    _TITLE = 'Furr2005 - whole-body vitamin A metabolism in humans'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'M_1': 'vitamin_a_metabolism_state_1', 'M_2': 'vitamin_a_metabolism_state_2', 'M_4': 'vitamin_a_metabolism_state_3', 'M_5': 'vitamin_a_metabolism_state_4', 'M_6': 'vitamin_a_metabolism_state_5', 'M_7': 'vitamin_a_metabolism_state_6', 'M_1_0': 'vitamin_a_metabolism_state_7', 'M_2_0': 'vitamin_a_metabolism_state_8', 'M_4_0': 'vitamin_a_metabolism_state_9', 'M_5_0': 'vitamin_a_metabolism_state_10', 'M_6_0': 'vitamin_a_metabolism_state_11', 'M_7_0': 'vitamin_a_metabolism_state_12', 'M_3_1': 'vitamin_a_metabolism_state_13', 'M_3_2': 'vitamin_a_metabolism_state_14', 'M_3_3': 'vitamin_a_metabolism_state_15', 'M_3_4': 'vitamin_a_metabolism_state_16', 'M_3_5': 'vitamin_a_metabolism_state_17', 'M_3_6': 'vitamin_a_metabolism_state_18', 'M_3_7': 'vitamin_a_metabolism_state_19', 'M_3_8': 'vitamin_a_metabolism_state_20', 'M_3_1_0': 'vitamin_a_metabolism_state_21', 'M_3_2_0': 'vitamin_a_metabolism_state_22', 'M_3_3_0': 'vitamin_a_metabolism_state_23', 'M_3_4_0': 'vitamin_a_metabolism_state_24', 'M_3_5_0': 'vitamin_a_metabolism_state_25', 'M_3_6_0': 'vitamin_a_metabolism_state_26', 'M_3_7_0': 'vitamin_a_metabolism_state_27', 'M_3_8_0': 'vitamin_a_metabolism_state_28'}
    _OBSERVABLES = ['M_1', 'M_2', 'M_4', 'M_5', 'M_6', 'M_7', 'M_1_0', 'M_2_0', 'M_4_0', 'M_5_0', 'M_6_0', 'M_7_0', 'M_3_1', 'M_3_2', 'M_3_3', 'M_3_4', 'M_3_5', 'M_3_6', 'M_3_7', 'M_3_8', 'M_3_1_0', 'M_3_2_0', 'M_3_3_0', 'M_3_4_0', 'M_3_5_0', 'M_3_6_0', 'M_3_7_0', 'M_3_8_0']
    _SPECIES_LABELS = {'M_1': 'Vitamin A Metabolism state 1', 'M_2': 'Vitamin A Metabolism state 2', 'M_4': 'Vitamin A Metabolism state 3', 'M_5': 'Vitamin A Metabolism state 4', 'M_6': 'Vitamin A Metabolism state 5', 'M_7': 'Vitamin A Metabolism state 6', 'M_1_0': 'Vitamin A Metabolism state 7', 'M_2_0': 'Vitamin A Metabolism state 8', 'M_4_0': 'Vitamin A Metabolism state 9', 'M_5_0': 'Vitamin A Metabolism state 10', 'M_6_0': 'Vitamin A Metabolism state 11', 'M_7_0': 'Vitamin A Metabolism state 12', 'M_3_1': 'Vitamin A Metabolism state 13', 'M_3_2': 'Vitamin A Metabolism state 14', 'M_3_3': 'Vitamin A Metabolism state 15', 'M_3_4': 'Vitamin A Metabolism state 16', 'M_3_5': 'Vitamin A Metabolism state 17', 'M_3_6': 'Vitamin A Metabolism state 18', 'M_3_7': 'Vitamin A Metabolism state 19', 'M_3_8': 'Vitamin A Metabolism state 20', 'M_3_1_0': 'Vitamin A Metabolism state 21', 'M_3_2_0': 'Vitamin A Metabolism state 22', 'M_3_3_0': 'Vitamin A Metabolism state 23', 'M_3_4_0': 'Vitamin A Metabolism state 24', 'M_3_5_0': 'Vitamin A Metabolism state 25', 'M_3_6_0': 'Vitamin A Metabolism state 26', 'M_3_7_0': 'Vitamin A Metabolism state 27', 'M_3_8_0': 'Vitamin A Metabolism state 28'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_vitamin_a_metabolism_state_1': ('M_1', 0.7512690355, 'native SBML value', 'Initial condition for vitamin a metabolism state 1. Maps to bundled SBML symbol `M_1`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_vitamin_a_metabolism_state_2': ('M_2', 0.5416721566, 'native SBML value', 'Initial condition for vitamin a metabolism state 2. Maps to bundled SBML symbol `M_2`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_vitamin_a_metabolism_state_3': ('M_4', 3.731098421, 'native SBML value', 'Initial condition for vitamin a metabolism state 3. Maps to bundled SBML symbol `M_4`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_vitamin_a_metabolism_state_4': ('M_5', 3.17239151, 'native SBML value', 'Initial condition for vitamin a metabolism state 4. Maps to bundled SBML symbol `M_5`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_vitamin_a_metabolism_state_5': ('M_6', 231.4107506, 'native SBML value', 'Initial condition for vitamin a metabolism state 5. Maps to bundled SBML symbol `M_6`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'vitamin_a_metabolism_state_1': ('M_1', 'native SBML value', 'Vitamin A Metabolism state 1; conservative display label for an abstract SBML state variable. Maps to SBML symbol `M_1`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'vitamin_a_metabolism_state_2': ('M_2', 'native SBML value', 'Vitamin A Metabolism state 2; conservative display label for an abstract SBML state variable. Maps to SBML symbol `M_2`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'vitamin_a_metabolism_state_3': ('M_4', 'native SBML value', 'Vitamin A Metabolism state 3; conservative display label for an abstract SBML state variable. Maps to SBML symbol `M_4`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'vitamin_a_metabolism_state_4': ('M_5', 'native SBML value', 'Vitamin A Metabolism state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `M_5`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'vitamin_a_metabolism_state_5': ('M_6', 'native SBML value', 'Vitamin A Metabolism state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `M_6`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/MODEL2405200001.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
