# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for vanBeek2007_OxPhos_HeartMuscleCells."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Vanbeek2007OxphosHeartmusclecellsModel1006230027Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for vanBeek2007_OxPhos_HeartMuscleCells."""

    _SBML_ID = 'MODEL1006230027'
    _TITLE = 'vanBeek2007_OxPhos_HeartMuscleCells'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'ATP_cyt': 'cytosolic_atp', 'ADP_cyt': 'cytosolic_adp', 'PCr_cyt': 'mitochondrial_energy_state_3_cytosolic', 'Cr_cyt': 'mitochondrial_energy_state_4_cytosolic', 'Pi_cyt': 'mitochondrial_energy_state_5_cytosolic', 'ATP_ims': 'mitochondrial_energy_state_6', 'ADP_ims': 'mitochondrial_energy_state_7', 'PCr_ims': 'mitochondrial_energy_state_8', 'Cr_ims': 'mitochondrial_energy_state_9', 'Pi_ims': 'mitochondrial_energy_state_10', 'J_CKMM': 'mitochondrial_energy_state_11', 'Den_MMCK': 'mitochondrial_energy_state_12', 'Kc_J_CKMM': 'mitochondrial_energy_state_13', 'KIb_J_CKMM': 'mitochondrial_energy_state_14', 'J_CKMi': 'mitochondrial_energy_state_15', 'Den_MiCK': 'mitochondrial_energy_state_16', 'Kc_J_CKMi': 'mitochondrial_energy_state_17', 'KIb_J_CKMi': 'mitochondrial_energy_state_18', 't_cycle_1': 'mitochondrial_energy_state_19', 't_cycle_2': 'mitochondrial_energy_state_20', 'duration_1': 'mitochondrial_energy_state_21', 'ltime': 'mitochondrial_energy_state_22', 't_cycle': 'mitochondrial_energy_state_23', 'H_ATPmax': 'mitochondrial_energy_state_24', 'J_hyd': 'mitochondrial_energy_state_25', 'J_syn': 'mitochondrial_energy_state_26', 'Den_syn': 'mitochondrial_energy_state_27', 'J_diff_ATP': 'mitochondrial_energy_state_28', 'J_diff_ADP': 'mitochondrial_energy_state_29', 'J_diff_PCr': 'mitochondrial_energy_state_30', 'J_diff_Cr': 'mitochondrial_energy_state_31', 'J_diff_Pi': 'mitochondrial_energy_state_32'}
    _OBSERVABLES = ['ATP_cyt', 'ADP_cyt', 'PCr_cyt', 'Cr_cyt', 'Pi_cyt', 'ATP_ims', 'ADP_ims', 'PCr_ims', 'Cr_ims', 'Pi_ims', 'J_CKMM', 'Den_MMCK', 'Kc_J_CKMM', 'KIb_J_CKMM', 'J_CKMi', 'Den_MiCK', 'Kc_J_CKMi', 'KIb_J_CKMi', 't_cycle_1', 't_cycle_2', 'duration_1', 'ltime', 't_cycle', 'H_ATPmax', 'J_hyd', 'J_syn', 'Den_syn', 'J_diff_ATP', 'J_diff_ADP', 'J_diff_PCr', 'J_diff_Cr', 'J_diff_Pi']
    _SPECIES_LABELS = {'ATP_cyt': 'Cytosolic ATP', 'ADP_cyt': 'Cytosolic ADP', 'PCr_cyt': 'Mitochondrial Energy state 3 cytosolic', 'Cr_cyt': 'Mitochondrial Energy state 4 cytosolic', 'Pi_cyt': 'Mitochondrial Energy state 5 cytosolic', 'ATP_ims': 'Mitochondrial Energy state 6', 'ADP_ims': 'Mitochondrial Energy state 7', 'PCr_ims': 'Mitochondrial Energy state 8', 'Cr_ims': 'Mitochondrial Energy state 9', 'Pi_ims': 'Mitochondrial Energy state 10', 'J_CKMM': 'Mitochondrial Energy state 11', 'Den_MMCK': 'Mitochondrial Energy state 12', 'Kc_J_CKMM': 'Mitochondrial Energy state 13', 'KIb_J_CKMM': 'Mitochondrial Energy state 14', 'J_CKMi': 'Mitochondrial Energy state 15', 'Den_MiCK': 'Mitochondrial Energy state 16', 'Kc_J_CKMi': 'Mitochondrial Energy state 17', 'KIb_J_CKMi': 'Mitochondrial Energy state 18', 't_cycle_1': 'Mitochondrial Energy state 19', 't_cycle_2': 'Mitochondrial Energy state 20', 'duration_1': 'Mitochondrial Energy state 21', 'ltime': 'Mitochondrial Energy state 22', 't_cycle': 'Mitochondrial Energy state 23', 'H_ATPmax': 'Mitochondrial Energy state 24', 'J_hyd': 'Mitochondrial Energy state 25', 'J_syn': 'Mitochondrial Energy state 26', 'Den_syn': 'Mitochondrial Energy state 27', 'J_diff_ATP': 'Mitochondrial Energy state 28', 'J_diff_ADP': 'Mitochondrial Energy state 29', 'J_diff_PCr': 'Mitochondrial Energy state 30', 'J_diff_Cr': 'Mitochondrial Energy state 31', 'J_diff_Pi': 'Mitochondrial Energy state 32'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_cytosolic_atp': ('ATP_cyt', 5912.77, 'native SBML value', 'Initial condition for cytosolic atp. Maps to bundled SBML symbol `ATP_cyt`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_cytosolic_adp': ('ADP_cyt', 64.0, 'native SBML value', 'Initial condition for cytosolic adp. Maps to bundled SBML symbol `ADP_cyt`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_mitochondrial_energy_state_3_cytosolic': ('PCr_cyt', 5000.0, 'native SBML value', 'Initial condition for mitochondrial energy state 3 cytosolic. Maps to bundled SBML symbol `PCr_cyt`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_mitochondrial_energy_state_4_cytosolic': ('Cr_cyt', 10500.0, 'native SBML value', 'Initial condition for mitochondrial energy state 4 cytosolic. Maps to bundled SBML symbol `Cr_cyt`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_mitochondrial_energy_state_5_cytosolic': ('Pi_cyt', 913.0, 'native SBML value', 'Initial condition for mitochondrial energy state 5 cytosolic. Maps to bundled SBML symbol `Pi_cyt`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'cytosolic_atp': ('ATP_cyt', 'native SBML value', 'Cytosolic ATP. Maps to SBML symbol `ATP_cyt`.'), 'cytosolic_adp': ('ADP_cyt', 'native SBML value', 'Cytosolic ADP. Maps to SBML symbol `ADP_cyt`.'), 'mitochondrial_energy_state_3_cytosolic': ('PCr_cyt', 'native SBML value', 'Mitochondrial Energy state 3 cytosolic; conservative display label for an abstract SBML state variable. Maps to SBML symbol `PCr_cyt`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'mitochondrial_energy_state_4_cytosolic': ('Cr_cyt', 'native SBML value', 'Mitochondrial Energy state 4 cytosolic; conservative display label for an abstract SBML state variable. Maps to SBML symbol `Cr_cyt`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'mitochondrial_energy_state_5_cytosolic': ('Pi_cyt', 'native SBML value', 'Mitochondrial Energy state 5 cytosolic; conservative display label for an abstract SBML state variable. Maps to SBML symbol `Pi_cyt`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/MODEL1006230027.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
