# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Oliveira2020 - E. coli Extended Central Carbon Metabolism from Glycerol."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Oliveira2020EColiExtendedCentralCarbonMetaModel2010160002Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Oliveira2020 - E. coli Extended Central Carbon Metabolism from Glycerol."""

    _SBML_ID = 'MODEL2010160002'
    _TITLE = 'Oliveira2020 - E. coli Extended Central Carbon Metabolism from Glycerol'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'ACCOA': 'glycolysis_state_1', 'ACO': 'glycolysis_state_2', 'ACP': 'glycolysis_state_3', 'AKG': 'glycolysis_state_4', 'BPG': 'glycolysis_state_5', 'CIT': 'glycolysis_state_6', 'DAP': 'glycolysis_state_7', 'E4P': 'glycolysis_state_8', 'F6P': 'fructose_6_phosphate', 'FDP': 'glycolysis_state_10', 'FUM': 'glycolysis_state_11', 'G6P': 'glucose_6_phosphate', 'GAP': 'glyceraldehyde_3_phosphate', 'GL6P': 'glycolysis_state_14', 'GLX': 'glycolysis_state_15', 'ICIT': 'glycolysis_state_16', 'KDPG': 'glycolysis_state_17', 'MAL': 'glycolysis_state_18', 'NAD': 'nad', 'NADH': 'nadh', 'NADP': 'nadp', 'NADPH': 'nadph', 'OAA': 'glycolysis_state_23', 'PEP': 'phosphoenolpyruvate', 'PGA2': 'glycolysis_state_25', 'PGA3': 'glycolysis_state_26', 'PGN': 'glycolysis_state_27', 'PYR': 'pyruvate', 'Q': 'glycolysis_state_29', 'QH2': 'glycolysis_state_30', 'R5P': 'glycolysis_state_31', 'RU5P': 'glycolysis_state_32', 'S7P': 'glycolysis_state_33', 'SUC': 'glycolysis_state_34', 'SUCCOA': 'glycolysis_state_35', 'X5P': 'glycolysis_state_36', 'ei': 'glycolysis_state_37', 'eiP': 'glycolysis_state_38', 'eiia': 'glycolysis_state_39', 'eiiaP': 'glycolysis_state_40', 'eiicb': 'glycolysis_state_41', 'eiicbP': 'glycolysis_state_42', 'hpr': 'glycolysis_state_43', 'hprP': 'glycolysis_state_44', 'icd': 'glycolysis_state_45', 'icdP': 'glycolysis_state_46', 'tal': 'glycolysis_state_47', 'talC3': 'glycolysis_state_48', 'tkt': 'glycolysis_state_49', 'tktC2': 'glycolysis_state_50', 'ADP': 'adp', 'AMP': 'amp', 'ATP': 'atp', 'CAMP': 'glycolysis_state_54', 'P': 'glycolysis_state_55', 'ASP': 'glycolysis_state_56', 'FAD': 'glycolysis_state_57', 'FADH2': 'glycolysis_state_58', 'ACEx': 'ace', 'GLCx': 'glycolysis_state_60', 'ACEx_0': 'extracellular_acetate', 'Hout': 'glycolysis_state_62', 'GLCp': 'glycolysis_state_63', 'Pp': 'glycolysis_state_64', 'ACEp': 'glycolysis_state_65', 'G3P': 'glycolysis_state_66', 'GLY': 'glycolysis_state_67', 'MCOA': 'glycolysis_state_68', 'LGLU': 'glycolysis_state_69', 'BA': 'glycolysis_state_70', 'MCOAp': 'glycolysis_state_71', 'MCOAx': 'glycolysis_state_72', 'BAp': 'glycolysis_state_73', 'BAx': 'glycolysis_state_74', 'GLYp': 'glycolysis_state_75', 'GLYx': 'glycolysis_state_76', 'DAH': 'glycolysis_state_77'}
    _OBSERVABLES = ['ACCOA', 'ACO', 'ACP', 'AKG', 'BPG', 'CIT', 'DAP', 'E4P', 'F6P', 'FDP', 'FUM', 'G6P', 'GAP', 'GL6P', 'GLX', 'ICIT', 'KDPG', 'MAL', 'NAD', 'NADH', 'NADP', 'NADPH', 'OAA', 'PEP', 'PGA2', 'PGA3', 'PGN', 'PYR', 'Q', 'QH2', 'R5P', 'RU5P', 'S7P', 'SUC', 'SUCCOA', 'X5P', 'ei', 'eiP', 'eiia', 'eiiaP', 'eiicb', 'eiicbP', 'hpr', 'hprP', 'icd', 'icdP', 'tal', 'talC3', 'tkt', 'tktC2', 'ADP', 'AMP', 'ATP', 'CAMP', 'P', 'ASP', 'FAD', 'FADH2', 'ACEx', 'GLCx', 'ACEx_0', 'Hout', 'GLCp', 'Pp', 'ACEp', 'G3P', 'GLY', 'MCOA', 'LGLU', 'BA', 'MCOAp', 'MCOAx', 'BAp', 'BAx', 'GLYp', 'GLYx', 'DAH']
    _SPECIES_LABELS = {'ACCOA': 'Glycolysis state 1', 'ACO': 'Glycolysis state 2', 'ACP': 'Glycolysis state 3', 'AKG': 'Glycolysis state 4', 'BPG': 'Glycolysis state 5', 'CIT': 'Glycolysis state 6', 'DAP': 'Glycolysis state 7', 'E4P': 'Glycolysis state 8', 'F6P': 'Fructose 6 Phosphate', 'FDP': 'Glycolysis state 10', 'FUM': 'Glycolysis state 11', 'G6P': 'Glucose 6 Phosphate', 'GAP': 'Glyceraldehyde 3 Phosphate', 'GL6P': 'Glycolysis state 14', 'GLX': 'Glycolysis state 15', 'ICIT': 'Glycolysis state 16', 'KDPG': 'Glycolysis state 17', 'MAL': 'Glycolysis state 18', 'NAD': 'NAD', 'NADH': 'NADH', 'NADP': 'NADP', 'NADPH': 'NADPH', 'OAA': 'Glycolysis state 23', 'PEP': 'Phosphoenolpyruvate', 'PGA2': 'Glycolysis state 25', 'PGA3': 'Glycolysis state 26', 'PGN': 'Glycolysis state 27', 'PYR': 'Pyruvate', 'Q': 'Glycolysis state 29', 'QH2': 'Glycolysis state 30', 'R5P': 'Glycolysis state 31', 'RU5P': 'Glycolysis state 32', 'S7P': 'Glycolysis state 33', 'SUC': 'Glycolysis state 34', 'SUCCOA': 'Glycolysis state 35', 'X5P': 'Glycolysis state 36', 'ei': 'Glycolysis state 37', 'eiP': 'Glycolysis state 38', 'eiia': 'Glycolysis state 39', 'eiiaP': 'Glycolysis state 40', 'eiicb': 'Glycolysis state 41', 'eiicbP': 'Glycolysis state 42', 'hpr': 'Glycolysis state 43', 'hprP': 'Glycolysis state 44', 'icd': 'Glycolysis state 45', 'icdP': 'Glycolysis state 46', 'tal': 'Glycolysis state 47', 'talC3': 'Glycolysis state 48', 'tkt': 'Glycolysis state 49', 'tktC2': 'Glycolysis state 50', 'ADP': 'ADP', 'AMP': 'AMP', 'ATP': 'ATP', 'CAMP': 'Glycolysis state 54', 'P': 'Glycolysis state 55', 'ASP': 'Glycolysis state 56', 'FAD': 'Glycolysis state 57', 'FADH2': 'Glycolysis state 58', 'ACEx': 'ACE', 'GLCx': 'Glycolysis state 60', 'ACEx_0': 'extracellular acetate', 'Hout': 'Glycolysis state 62', 'GLCp': 'Glycolysis state 63', 'Pp': 'Glycolysis state 64', 'ACEp': 'Glycolysis state 65', 'G3P': 'Glycolysis state 66', 'GLY': 'Glycolysis state 67', 'MCOA': 'Glycolysis state 68', 'LGLU': 'Glycolysis state 69', 'BA': 'Glycolysis state 70', 'MCOAp': 'Glycolysis state 71', 'MCOAx': 'Glycolysis state 72', 'BAp': 'Glycolysis state 73', 'BAx': 'Glycolysis state 74', 'GLYp': 'Glycolysis state 75', 'GLYx': 'Glycolysis state 76', 'DAH': 'Glycolysis state 77'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_glycolysis_state_1': ('ACCOA', 0.142215148385023, 'native SBML value', 'Initial condition for glycolysis state 1. Maps to bundled SBML symbol `ACCOA`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_2': ('ACO', 0.0460024355785109, 'native SBML value', 'Initial condition for glycolysis state 2. Maps to bundled SBML symbol `ACO`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_3': ('ACP', 0.0282547194235527, 'native SBML value', 'Initial condition for glycolysis state 3. Maps to bundled SBML symbol `ACP`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_4': ('AKG', 0.309617017238334, 'native SBML value', 'Initial condition for glycolysis state 4. Maps to bundled SBML symbol `AKG`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_5': ('BPG', 0.367267442064914, 'native SBML value', 'Initial condition for glycolysis state 5. Maps to bundled SBML symbol `BPG`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'glycolysis_state_1': ('ACCOA', 'native SBML value', 'Glycolysis state 1; conservative display label for an abstract SBML state variable. Maps to SBML symbol `ACCOA`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glycolysis_state_2': ('ACO', 'native SBML value', 'Glycolysis state 2; conservative display label for an abstract SBML state variable. Maps to SBML symbol `ACO`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glycolysis_state_3': ('ACP', 'native SBML value', 'Glycolysis state 3; conservative display label for an abstract SBML state variable. Maps to SBML symbol `ACP`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glycolysis_state_4': ('AKG', 'native SBML value', 'Glycolysis state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `AKG`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glycolysis_state_5': ('BPG', 'native SBML value', 'Glycolysis state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `BPG`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/MODEL2010160002.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
