# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Sips2015 - Glucose and non-esterified fatty acids (NEFA) metabolism."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Sips2015GlucoseAndNonEsterifiedFattyAcidsModel1806080001Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Sips2015 - Glucose and non-esterified fatty acids (NEFA) metabolism."""

    _SBML_ID = 'MODEL1806080001'
    _TITLE = 'Sips2015 - Glucose and non-esterified fatty acids (NEFA) metabolism'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'m_4': 'glycolysis_state_1', 'm_2': 'glycolysis_state_2', 'm_6': 'glycolysis_state_3', 'S_b_minus': 'glycolysis_state_4', 'k_p1': 'glycolysis_state_5', 'V_m0': 'glycolysis_state_6', 'aa': 'glycolysis_state_7', 'cc': 'glycolysis_state_8', 'EGP': 'glycolysis_state_9', 'V_mmax': 'glycolysis_state_10', 'E': 'glycolysis_state_11', 'S': 'glycolysis_state_12', 'I': 'glycolysis_state_13', 'G': 'glycolysis_state_14', 'HE': 'glycolysis_state_15', 'm_3': 'glycolysis_state_16', 'Q_sto': 'glycolysis_state_17', 'Ra': 'glycolysis_state_18', 'k_empt': 'glycolysis_state_19', 'U_idm': 'glycolysis_state_20', 'U_id': 'glycolysis_state_21', 'U': 'glycolysis_state_22', 'parameter_20': 'glycolysis_state_23', 'parameter_22': 'glycolysis_state_24', 'parameter_23': 'glycolysis_state_25', 'parameter_24': 'glycolysis_state_26', 'parameter_26': 'glycolysis_state_27', 'parameter_28': 'triglyceride', 'parameter_27': 'glycolysis_state_29', 'parameter_25': 'glycolysis_state_30', 'parameter_34': 'glycolysis_state_31', 'S_po': 'glycolysis_state_32', 'parameter_35': 'plot1tot2', 'parameter_36': 'plot2togut', 'G_p': 'glycolysis_state_35', 'G_t': 'glycolysis_state_36', 'I_l': 'glycolysis_state_37', 'I_p': 'glycolysis_state_38', 'Q_sto1': 'glycolysis_state_39', 'Q_gut': 'glycolysis_state_40', 'I_1': 'glycolysis_state_41', 'I_d': 'glycolysis_state_42', 'X': 'glycolysis_state_43', 'I_po': 'glycolysis_state_44', 'Y': 'glycolysis_state_45', 'Q_sto2': 'glycolysis_state_46', 'species_1': 'glycolysis_state_47', 'species_2': 'glycolysis_state_48', 'species_3': 'glycolysis_state_49', 'species_4': 'non_esterified_fatty_acids', 'species_5': 'glycolysis_state_51', 'species_6': 'glycolysis_state_52'}
    _OBSERVABLES = ['m_4', 'm_2', 'm_6', 'S_b_minus', 'k_p1', 'V_m0', 'aa', 'cc', 'EGP', 'V_mmax', 'E', 'S', 'I', 'G', 'HE', 'm_3', 'Q_sto', 'Ra', 'k_empt', 'U_idm', 'U_id', 'U', 'parameter_20', 'parameter_22', 'parameter_23', 'parameter_24', 'parameter_26', 'parameter_28', 'parameter_27', 'parameter_25', 'parameter_34', 'S_po', 'parameter_35', 'parameter_36', 'G_p', 'G_t', 'I_l', 'I_p', 'Q_sto1', 'Q_gut', 'I_1', 'I_d', 'X', 'I_po', 'Y', 'Q_sto2', 'species_1', 'species_2', 'species_3', 'species_4', 'species_5', 'species_6']
    _SPECIES_LABELS = {'m_4': 'Glycolysis state 1', 'm_2': 'Glycolysis state 2', 'm_6': 'Glycolysis state 3', 'S_b_minus': 'Glycolysis state 4', 'k_p1': 'Glycolysis state 5', 'V_m0': 'Glycolysis state 6', 'aa': 'Glycolysis state 7', 'cc': 'Glycolysis state 8', 'EGP': 'Glycolysis state 9', 'V_mmax': 'Glycolysis state 10', 'E': 'Glycolysis state 11', 'S': 'Glycolysis state 12', 'I': 'Glycolysis state 13', 'G': 'Glycolysis state 14', 'HE': 'Glycolysis state 15', 'm_3': 'Glycolysis state 16', 'Q_sto': 'Glycolysis state 17', 'Ra': 'Glycolysis state 18', 'k_empt': 'Glycolysis state 19', 'U_idm': 'Glycolysis state 20', 'U_id': 'Glycolysis state 21', 'U': 'Glycolysis state 22', 'parameter_20': 'Glycolysis state 23', 'parameter_22': 'Glycolysis state 24', 'parameter_23': 'Glycolysis state 25', 'parameter_24': 'Glycolysis state 26', 'parameter_26': 'Glycolysis state 27', 'parameter_28': 'triglyceride', 'parameter_27': 'Glycolysis state 29', 'parameter_25': 'Glycolysis state 30', 'parameter_34': 'Glycolysis state 31', 'S_po': 'Glycolysis state 32', 'parameter_35': 'Plot1tot2', 'parameter_36': 'Plot2togut', 'G_p': 'Glycolysis state 35', 'G_t': 'Glycolysis state 36', 'I_l': 'Glycolysis state 37', 'I_p': 'Glycolysis state 38', 'Q_sto1': 'Glycolysis state 39', 'Q_gut': 'Glycolysis state 40', 'I_1': 'Glycolysis state 41', 'I_d': 'Glycolysis state 42', 'X': 'Glycolysis state 43', 'I_po': 'Glycolysis state 44', 'Y': 'Glycolysis state 45', 'Q_sto2': 'Glycolysis state 46', 'species_1': 'Glycolysis state 47', 'species_2': 'Glycolysis state 48', 'species_3': 'Glycolysis state 49', 'species_4': 'non esterified fatty acids', 'species_5': 'Glycolysis state 51', 'species_6': 'Glycolysis state 52'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_glycolysis_state_1': ('m_4', 0.0982882779338853, 'native SBML value', 'Initial condition for glycolysis state 1. Maps to bundled SBML symbol `m_4`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_2': ('m_2', 0.245720694834713, 'native SBML value', 'Initial condition for glycolysis state 2. Maps to bundled SBML symbol `m_2`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_3': ('m_6', 0.64712, 'native SBML value', 'Initial condition for glycolysis state 3. Maps to bundled SBML symbol `m_6`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_4': ('S_b_minus', -1.55, 'native SBML value', 'Initial condition for glycolysis state 4. Maps to bundled SBML symbol `S_b_minus`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_5': ('k_p1', 2.4642129350853, 'native SBML value', 'Initial condition for glycolysis state 5. Maps to bundled SBML symbol `k_p1`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'glycolysis_state_1': ('m_4', 'native SBML value', 'Glycolysis state 1; conservative display label for an abstract SBML state variable. Maps to SBML symbol `m_4`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glycolysis_state_2': ('m_2', 'native SBML value', 'Glycolysis state 2; conservative display label for an abstract SBML state variable. Maps to SBML symbol `m_2`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glycolysis_state_3': ('m_6', 'native SBML value', 'Glycolysis state 3; conservative display label for an abstract SBML state variable. Maps to SBML symbol `m_6`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glycolysis_state_4': ('S_b_minus', 'native SBML value', 'Glycolysis state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `S_b_minus`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glycolysis_state_5': ('k_p1', 'native SBML value', 'Glycolysis state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `k_p1`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/MODEL1806080001.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
