# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Green2024 - whole-body vitamin A metabolism in humans."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Green2024WholeBodyVitaminAMetabolismInHumModel2411290001Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Green2024 - whole-body vitamin A metabolism in humans."""

    _SBML_ID = 'MODEL2411290001'
    _TITLE = 'Green2024 - whole-body vitamin A metabolism in humans'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'M_1': 'vitamin_a_metabolism_state_1', 'M_2': 'vitamin_a_metabolism_state_2', 'M_4': 'vitamin_a_metabolism_state_3', 'M_5': 'vitamin_a_metabolism_state_4', 'M_6': 'vitamin_a_metabolism_state_5', 'M_7': 'vitamin_a_metabolism_state_6', 'M_1_0': 'vitamin_a_metabolism_state_7', 'M_2_0': 'vitamin_a_metabolism_state_8', 'M_4_0': 'vitamin_a_metabolism_state_9', 'M_5_0': 'vitamin_a_metabolism_state_10', 'M_6_0': 'vitamin_a_metabolism_state_11', 'M_7_0': 'vitamin_a_metabolism_state_12', 'M_3_1': 'vitamin_a_metabolism_state_13', 'M_3_2': 'vitamin_a_metabolism_state_14', 'M_3_3': 'vitamin_a_metabolism_state_15', 'M_3_4': 'vitamin_a_metabolism_state_16', 'M_3_5': 'vitamin_a_metabolism_state_17', 'M_3_6': 'vitamin_a_metabolism_state_18', 'M_3_7': 'vitamin_a_metabolism_state_19', 'M_3_8': 'vitamin_a_metabolism_state_20', 'M_3_1_0': 'vitamin_a_metabolism_state_21', 'M_3_2_0': 'vitamin_a_metabolism_state_22', 'M_3_3_0': 'vitamin_a_metabolism_state_23', 'M_3_4_0': 'vitamin_a_metabolism_state_24', 'M_3_5_0': 'vitamin_a_metabolism_state_25', 'M_3_6_0': 'vitamin_a_metabolism_state_26', 'M_3_7_0': 'vitamin_a_metabolism_state_27', 'M_3_8_0': 'vitamin_a_metabolism_state_28', 'M_8_1': 'vitamin_a_metabolism_state_29', 'M_8_2': 'vitamin_a_metabolism_state_30', 'M_8_3': 'vitamin_a_metabolism_state_31', 'M_8_4': 'vitamin_a_metabolism_state_32', 'M_8_5': 'vitamin_a_metabolism_state_33', 'M_8_6': 'vitamin_a_metabolism_state_34', 'M_8_7': 'vitamin_a_metabolism_state_35', 'M_8_8': 'vitamin_a_metabolism_state_36', 'M_8_1_0': 'vitamin_a_metabolism_state_37', 'M_8_2_0': 'vitamin_a_metabolism_state_38', 'M_8_3_0': 'vitamin_a_metabolism_state_39', 'M_8_4_0': 'vitamin_a_metabolism_state_40', 'M_8_5_0': 'vitamin_a_metabolism_state_41', 'M_8_6_0': 'vitamin_a_metabolism_state_42', 'M_8_7_0': 'vitamin_a_metabolism_state_43', 'M_8_8_0': 'vitamin_a_metabolism_state_44'}
    _OBSERVABLES = ['M_1', 'M_2', 'M_4', 'M_5', 'M_6', 'M_7', 'M_1_0', 'M_2_0', 'M_4_0', 'M_5_0', 'M_6_0', 'M_7_0', 'M_3_1', 'M_3_2', 'M_3_3', 'M_3_4', 'M_3_5', 'M_3_6', 'M_3_7', 'M_3_8', 'M_3_1_0', 'M_3_2_0', 'M_3_3_0', 'M_3_4_0', 'M_3_5_0', 'M_3_6_0', 'M_3_7_0', 'M_3_8_0', 'M_8_1', 'M_8_2', 'M_8_3', 'M_8_4', 'M_8_5', 'M_8_6', 'M_8_7', 'M_8_8', 'M_8_1_0', 'M_8_2_0', 'M_8_3_0', 'M_8_4_0', 'M_8_5_0', 'M_8_6_0', 'M_8_7_0', 'M_8_8_0']
    _SPECIES_LABELS = {'M_1': 'Vitamin A Metabolism state 1', 'M_2': 'Vitamin A Metabolism state 2', 'M_4': 'Vitamin A Metabolism state 3', 'M_5': 'Vitamin A Metabolism state 4', 'M_6': 'Vitamin A Metabolism state 5', 'M_7': 'Vitamin A Metabolism state 6', 'M_1_0': 'Vitamin A Metabolism state 7', 'M_2_0': 'Vitamin A Metabolism state 8', 'M_4_0': 'Vitamin A Metabolism state 9', 'M_5_0': 'Vitamin A Metabolism state 10', 'M_6_0': 'Vitamin A Metabolism state 11', 'M_7_0': 'Vitamin A Metabolism state 12', 'M_3_1': 'Vitamin A Metabolism state 13', 'M_3_2': 'Vitamin A Metabolism state 14', 'M_3_3': 'Vitamin A Metabolism state 15', 'M_3_4': 'Vitamin A Metabolism state 16', 'M_3_5': 'Vitamin A Metabolism state 17', 'M_3_6': 'Vitamin A Metabolism state 18', 'M_3_7': 'Vitamin A Metabolism state 19', 'M_3_8': 'Vitamin A Metabolism state 20', 'M_3_1_0': 'Vitamin A Metabolism state 21', 'M_3_2_0': 'Vitamin A Metabolism state 22', 'M_3_3_0': 'Vitamin A Metabolism state 23', 'M_3_4_0': 'Vitamin A Metabolism state 24', 'M_3_5_0': 'Vitamin A Metabolism state 25', 'M_3_6_0': 'Vitamin A Metabolism state 26', 'M_3_7_0': 'Vitamin A Metabolism state 27', 'M_3_8_0': 'Vitamin A Metabolism state 28', 'M_8_1': 'Vitamin A Metabolism state 29', 'M_8_2': 'Vitamin A Metabolism state 30', 'M_8_3': 'Vitamin A Metabolism state 31', 'M_8_4': 'Vitamin A Metabolism state 32', 'M_8_5': 'Vitamin A Metabolism state 33', 'M_8_6': 'Vitamin A Metabolism state 34', 'M_8_7': 'Vitamin A Metabolism state 35', 'M_8_8': 'Vitamin A Metabolism state 36', 'M_8_1_0': 'Vitamin A Metabolism state 37', 'M_8_2_0': 'Vitamin A Metabolism state 38', 'M_8_3_0': 'Vitamin A Metabolism state 39', 'M_8_4_0': 'Vitamin A Metabolism state 40', 'M_8_5_0': 'Vitamin A Metabolism state 41', 'M_8_6_0': 'Vitamin A Metabolism state 42', 'M_8_7_0': 'Vitamin A Metabolism state 43', 'M_8_8_0': 'Vitamin A Metabolism state 44'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_vitamin_a_metabolism_state_1': ('M_1', 0.04343260815, 'native SBML value', 'Initial condition for vitamin a metabolism state 1. Maps to bundled SBML symbol `M_1`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_vitamin_a_metabolism_state_2': ('M_2', 0.04300258233, 'native SBML value', 'Initial condition for vitamin a metabolism state 2. Maps to bundled SBML symbol `M_2`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_vitamin_a_metabolism_state_3': ('M_4', 1.36312171, 'native SBML value', 'Initial condition for vitamin a metabolism state 3. Maps to bundled SBML symbol `M_4`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_vitamin_a_metabolism_state_4': ('M_5', 3.361993214, 'native SBML value', 'Initial condition for vitamin a metabolism state 4. Maps to bundled SBML symbol `M_5`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_vitamin_a_metabolism_state_5': ('M_6', 920.4583274, 'native SBML value', 'Initial condition for vitamin a metabolism state 5. Maps to bundled SBML symbol `M_6`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'vitamin_a_metabolism_state_1': ('M_1', 'native SBML value', 'Vitamin A Metabolism state 1; conservative display label for an abstract SBML state variable. Maps to SBML symbol `M_1`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'vitamin_a_metabolism_state_2': ('M_2', 'native SBML value', 'Vitamin A Metabolism state 2; conservative display label for an abstract SBML state variable. Maps to SBML symbol `M_2`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'vitamin_a_metabolism_state_3': ('M_4', 'native SBML value', 'Vitamin A Metabolism state 3; conservative display label for an abstract SBML state variable. Maps to SBML symbol `M_4`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'vitamin_a_metabolism_state_4': ('M_5', 'native SBML value', 'Vitamin A Metabolism state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `M_5`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'vitamin_a_metabolism_state_5': ('M_6', 'native SBML value', 'Vitamin A Metabolism state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `M_6`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/MODEL2411290001.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
