# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for vanEunen2013 - Network dynamics of fatty acid β-oxidation (steady-state model)."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Vaneunen2013NetworkDynamicsOfFattyAcidOxidBiomd0000000505Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for vanEunen2013 - Network dynamics of fatty acid β-oxidation (steady-state model)."""

    _SBML_ID = 'BIOMD0000000505'
    _TITLE = 'vanEunen2013 - Network dynamics of fatty acid β-oxidation (steady-state model)'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'C16AcylCarCYT': 'lipid_metabolism_state_1_cytosolic', 'C16AcylCarMAT': 'lipid_metabolism_state_2_mitochondrial', 'C16AcylCoAMAT': 'lipid_metabolism_state_3', 'C16EnoylCoAMAT': 'lipid_metabolism_state_4', 'C16HydroxyacylCoAMAT': 'lipid_metabolism_state_5', 'C16KetoacylCoAMAT': 'lipid_metabolism_state_6', 'C14AcylCarCYT': 'lipid_metabolism_state_7_cytosolic', 'C14AcylCarMAT': 'lipid_metabolism_state_8_mitochondrial', 'C14AcylCoAMAT': 'lipid_metabolism_state_9', 'C14EnoylCoAMAT': 'lipid_metabolism_state_10', 'C14HydroxyacylCoAMAT': 'lipid_metabolism_state_11', 'C14KetoacylCoAMAT': 'lipid_metabolism_state_12', 'C12AcylCarCYT': 'lipid_metabolism_state_13_cytosolic', 'C12AcylCarMAT': 'lipid_metabolism_state_14_mitochondrial', 'C12AcylCoAMAT': 'lipid_metabolism_state_15', 'C12EnoylCoAMAT': 'lipid_metabolism_state_16', 'C12HydroxyacylCoAMAT': 'lipid_metabolism_state_17', 'C12KetoacylCoAMAT': 'lipid_metabolism_state_18', 'C10AcylCarCYT': 'lipid_metabolism_state_19_cytosolic', 'C10AcylCarMAT': 'lipid_metabolism_state_20_mitochondrial', 'C10AcylCoAMAT': 'lipid_metabolism_state_21', 'C10EnoylCoAMAT': 'lipid_metabolism_state_22', 'C10HydroxyacylCoAMAT': 'lipid_metabolism_state_23', 'C10KetoacylCoAMAT': 'lipid_metabolism_state_24', 'C8AcylCarCYT': 'lipid_metabolism_state_25_cytosolic', 'C8AcylCarMAT': 'lipid_metabolism_state_26_mitochondrial', 'C8AcylCoAMAT': 'lipid_metabolism_state_27', 'C8EnoylCoAMAT': 'lipid_metabolism_state_28', 'C8HydroxyacylCoAMAT': 'lipid_metabolism_state_29', 'C8KetoacylCoAMAT': 'lipid_metabolism_state_30', 'C6AcylCarCYT': 'lipid_metabolism_state_31_cytosolic', 'C6AcylCarMAT': 'lipid_metabolism_state_32_mitochondrial', 'C6AcylCoAMAT': 'lipid_metabolism_state_33', 'C6EnoylCoAMAT': 'lipid_metabolism_state_34', 'C6HydroxyacylCoAMAT': 'lipid_metabolism_state_35', 'C6KetoacylCoAMAT': 'lipid_metabolism_state_36', 'C4AcylCarCYT': 'lipid_metabolism_state_37_cytosolic', 'C4AcylCarMAT': 'lipid_metabolism_state_38_mitochondrial', 'C4AcylCoAMAT': 'lipid_metabolism_state_39', 'C4EnoylCoAMAT': 'lipid_metabolism_state_40', 'C4HydroxyacylCoAMAT': 'lipid_metabolism_state_41', 'C4AcetoacylCoAMAT': 'lipid_metabolism_state_42', 'AcetylCoAMAT': 'lipid_metabolism_state_43', 'FADHMAT': 'lipid_metabolism_state_44', 'NADHMAT': 'lipid_metabolism_state_45'}
    _OBSERVABLES = ['C16AcylCarCYT', 'C16AcylCarMAT', 'C16AcylCoAMAT', 'C16EnoylCoAMAT', 'C16HydroxyacylCoAMAT', 'C16KetoacylCoAMAT', 'C14AcylCarCYT', 'C14AcylCarMAT', 'C14AcylCoAMAT', 'C14EnoylCoAMAT', 'C14HydroxyacylCoAMAT', 'C14KetoacylCoAMAT', 'C12AcylCarCYT', 'C12AcylCarMAT', 'C12AcylCoAMAT', 'C12EnoylCoAMAT', 'C12HydroxyacylCoAMAT', 'C12KetoacylCoAMAT', 'C10AcylCarCYT', 'C10AcylCarMAT', 'C10AcylCoAMAT', 'C10EnoylCoAMAT', 'C10HydroxyacylCoAMAT', 'C10KetoacylCoAMAT', 'C8AcylCarCYT', 'C8AcylCarMAT', 'C8AcylCoAMAT', 'C8EnoylCoAMAT', 'C8HydroxyacylCoAMAT', 'C8KetoacylCoAMAT', 'C6AcylCarCYT', 'C6AcylCarMAT', 'C6AcylCoAMAT', 'C6EnoylCoAMAT', 'C6HydroxyacylCoAMAT', 'C6KetoacylCoAMAT', 'C4AcylCarCYT', 'C4AcylCarMAT', 'C4AcylCoAMAT', 'C4EnoylCoAMAT', 'C4HydroxyacylCoAMAT', 'C4AcetoacylCoAMAT', 'AcetylCoAMAT', 'FADHMAT', 'NADHMAT']
    _SPECIES_LABELS = {'C16AcylCarCYT': 'Lipid Metabolism state 1 cytosolic', 'C16AcylCarMAT': 'Lipid Metabolism state 2 mitochondrial', 'C16AcylCoAMAT': 'Lipid Metabolism state 3', 'C16EnoylCoAMAT': 'Lipid Metabolism state 4', 'C16HydroxyacylCoAMAT': 'Lipid Metabolism state 5', 'C16KetoacylCoAMAT': 'Lipid Metabolism state 6', 'C14AcylCarCYT': 'Lipid Metabolism state 7 cytosolic', 'C14AcylCarMAT': 'Lipid Metabolism state 8 mitochondrial', 'C14AcylCoAMAT': 'Lipid Metabolism state 9', 'C14EnoylCoAMAT': 'Lipid Metabolism state 10', 'C14HydroxyacylCoAMAT': 'Lipid Metabolism state 11', 'C14KetoacylCoAMAT': 'Lipid Metabolism state 12', 'C12AcylCarCYT': 'Lipid Metabolism state 13 cytosolic', 'C12AcylCarMAT': 'Lipid Metabolism state 14 mitochondrial', 'C12AcylCoAMAT': 'Lipid Metabolism state 15', 'C12EnoylCoAMAT': 'Lipid Metabolism state 16', 'C12HydroxyacylCoAMAT': 'Lipid Metabolism state 17', 'C12KetoacylCoAMAT': 'Lipid Metabolism state 18', 'C10AcylCarCYT': 'Lipid Metabolism state 19 cytosolic', 'C10AcylCarMAT': 'Lipid Metabolism state 20 mitochondrial', 'C10AcylCoAMAT': 'Lipid Metabolism state 21', 'C10EnoylCoAMAT': 'Lipid Metabolism state 22', 'C10HydroxyacylCoAMAT': 'Lipid Metabolism state 23', 'C10KetoacylCoAMAT': 'Lipid Metabolism state 24', 'C8AcylCarCYT': 'Lipid Metabolism state 25 cytosolic', 'C8AcylCarMAT': 'Lipid Metabolism state 26 mitochondrial', 'C8AcylCoAMAT': 'Lipid Metabolism state 27', 'C8EnoylCoAMAT': 'Lipid Metabolism state 28', 'C8HydroxyacylCoAMAT': 'Lipid Metabolism state 29', 'C8KetoacylCoAMAT': 'Lipid Metabolism state 30', 'C6AcylCarCYT': 'Lipid Metabolism state 31 cytosolic', 'C6AcylCarMAT': 'Lipid Metabolism state 32 mitochondrial', 'C6AcylCoAMAT': 'Lipid Metabolism state 33', 'C6EnoylCoAMAT': 'Lipid Metabolism state 34', 'C6HydroxyacylCoAMAT': 'Lipid Metabolism state 35', 'C6KetoacylCoAMAT': 'Lipid Metabolism state 36', 'C4AcylCarCYT': 'Lipid Metabolism state 37 cytosolic', 'C4AcylCarMAT': 'Lipid Metabolism state 38 mitochondrial', 'C4AcylCoAMAT': 'Lipid Metabolism state 39', 'C4EnoylCoAMAT': 'Lipid Metabolism state 40', 'C4HydroxyacylCoAMAT': 'Lipid Metabolism state 41', 'C4AcetoacylCoAMAT': 'Lipid Metabolism state 42', 'AcetylCoAMAT': 'Lipid Metabolism state 43', 'FADHMAT': 'Lipid Metabolism state 44', 'NADHMAT': 'Lipid Metabolism state 45'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_lipid_metabolism_state_1_cytosolic': ('C16AcylCarCYT', 0.0, 'native SBML value', 'Initial condition for lipid metabolism state 1 cytosolic. Maps to bundled SBML symbol `C16AcylCarCYT`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_lipid_metabolism_state_2_mitochondrial': ('C16AcylCarMAT', 0.0, 'native SBML value', 'Initial condition for lipid metabolism state 2 mitochondrial. Maps to bundled SBML symbol `C16AcylCarMAT`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_lipid_metabolism_state_3': ('C16AcylCoAMAT', 0.0, 'native SBML value', 'Initial condition for lipid metabolism state 3. Maps to bundled SBML symbol `C16AcylCoAMAT`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_lipid_metabolism_state_4': ('C16EnoylCoAMAT', 0.0, 'native SBML value', 'Initial condition for lipid metabolism state 4. Maps to bundled SBML symbol `C16EnoylCoAMAT`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_lipid_metabolism_state_5': ('C16HydroxyacylCoAMAT', 0.0, 'native SBML value', 'Initial condition for lipid metabolism state 5. Maps to bundled SBML symbol `C16HydroxyacylCoAMAT`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'lipid_metabolism_state_1_cytosolic': ('C16AcylCarCYT', 'native SBML value', 'Lipid Metabolism state 1 cytosolic; conservative display label for an abstract SBML state variable. Maps to SBML symbol `C16AcylCarCYT`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'lipid_metabolism_state_2_mitochondrial': ('C16AcylCarMAT', 'native SBML value', 'Lipid Metabolism state 2 mitochondrial; conservative display label for an abstract SBML state variable. Maps to SBML symbol `C16AcylCarMAT`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'lipid_metabolism_state_3': ('C16AcylCoAMAT', 'native SBML value', 'Lipid Metabolism state 3; conservative display label for an abstract SBML state variable. Maps to SBML symbol `C16AcylCoAMAT`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'lipid_metabolism_state_4': ('C16EnoylCoAMAT', 'native SBML value', 'Lipid Metabolism state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `C16EnoylCoAMAT`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'lipid_metabolism_state_5': ('C16HydroxyacylCoAMAT', 'native SBML value', 'Lipid Metabolism state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `C16HydroxyacylCoAMAT`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/BIOMD0000000505.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
