# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Bulik2016 - Regulation of hepatic glucose metabolism."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Bulik2016RegulationOfHepaticGlucoseMetaboliBiomd0000000633Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Bulik2016 - Regulation of hepatic glucose metabolism."""

    _SBML_ID = 'BIOMD0000000633'
    _TITLE = 'Bulik2016 - Regulation of hepatic glucose metabolism'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'glc_ext': 'extracellular_glucose', 'lac_ext': 'extracellular_lactate', 'glc': 'glucose', 'glc6p': 'glycolysis_state_4', 'glc1p': 'glycolysis_state_5', 'udpglc': 'glycolysis_state_6', 'glyglc': 'glycolysis_state_7', 'fru6p': 'fructose_6_phosphate', 'fru16bp': 'glycolysis_state_9', 'fru26bp': 'glycolysis_state_10', 'gap': 'glyceraldehyde_3_phosphate', 'dhap': 'glycolysis_state_12', 'bpg13': 'glycolysis_state_13', 'pg3': 'glycolysis_state_14', 'pg2': 'glycolysis_state_15', 'pep': 'phosphoenolpyruvate', 'pyr': 'pyruvate', 'oa': 'glycolysis_state_18', 'lac': 'lactate', 'mal': 'glycolysis_state_20', 'cit': 'glycolysis_state_21', 'h': 'glycolysis_state_22', 'co2_mito': 'glycolysis_state_23', 'oa_mito': 'glycolysis_state_24', 'pep_mito': 'glycolysis_state_25', 'pyr_mito': 'glycolysis_state_26', 'mal_mito': 'glycolysis_state_27', 'p_mito': 'glycolysis_state_28', 'h_mito': 'glycolysis_state_29', 'glc_er': 'glycolysis_state_30', 'glc6p_er': 'glycolysis_state_31', 'atp': 'atp', 'adp': 'adp', 'amp': 'amp', 'utp': 'glycolysis_state_35', 'udp': 'glycolysis_state_36', 'gtp': 'glycolysis_state_37', 'gdp': 'glycolysis_state_38', 'pp': 'glycolysis_state_39', 'p': 'glycolysis_state_40', 'p_er': 'glycolysis_state_41', 'co2': 'co2', 'nad': 'nad', 'nadh': 'nadh', 'atp_mito': 'glycolysis_state_45', 'adp_mito': 'glycolysis_state_46', 'gtp_mito': 'glycolysis_state_47', 'gdp_mito': 'glycolysis_state_48', 'nadh_mito': 'glycolysis_state_49', 'nad_mito': 'glycolysis_state_50'}
    _OBSERVABLES = ['glc_ext', 'lac_ext', 'glc', 'glc6p', 'glc1p', 'udpglc', 'glyglc', 'fru6p', 'fru16bp', 'fru26bp', 'gap', 'dhap', 'bpg13', 'pg3', 'pg2', 'pep', 'pyr', 'oa', 'lac', 'mal', 'cit', 'h', 'co2_mito', 'oa_mito', 'pep_mito', 'pyr_mito', 'mal_mito', 'p_mito', 'h_mito', 'glc_er', 'glc6p_er', 'atp', 'adp', 'amp', 'utp', 'udp', 'gtp', 'gdp', 'pp', 'p', 'p_er', 'co2', 'nad', 'nadh', 'atp_mito', 'adp_mito', 'gtp_mito', 'gdp_mito', 'nadh_mito', 'nad_mito']
    _SPECIES_LABELS = {'glc_ext': 'Extracellular Glucose', 'lac_ext': 'Extracellular Lactate', 'glc': 'Glucose', 'glc6p': 'Glycolysis state 4', 'glc1p': 'Glycolysis state 5', 'udpglc': 'Glycolysis state 6', 'glyglc': 'Glycolysis state 7', 'fru6p': 'Fructose 6 Phosphate', 'fru16bp': 'Glycolysis state 9', 'fru26bp': 'Glycolysis state 10', 'gap': 'Glyceraldehyde 3 Phosphate', 'dhap': 'Glycolysis state 12', 'bpg13': 'Glycolysis state 13', 'pg3': 'Glycolysis state 14', 'pg2': 'Glycolysis state 15', 'pep': 'Phosphoenolpyruvate', 'pyr': 'Pyruvate', 'oa': 'Glycolysis state 18', 'lac': 'Lactate', 'mal': 'Glycolysis state 20', 'cit': 'Glycolysis state 21', 'h': 'Glycolysis state 22', 'co2_mito': 'Glycolysis state 23', 'oa_mito': 'Glycolysis state 24', 'pep_mito': 'Glycolysis state 25', 'pyr_mito': 'Glycolysis state 26', 'mal_mito': 'Glycolysis state 27', 'p_mito': 'Glycolysis state 28', 'h_mito': 'Glycolysis state 29', 'glc_er': 'Glycolysis state 30', 'glc6p_er': 'Glycolysis state 31', 'atp': 'ATP', 'adp': 'ADP', 'amp': 'AMP', 'utp': 'Glycolysis state 35', 'udp': 'Glycolysis state 36', 'gtp': 'Glycolysis state 37', 'gdp': 'Glycolysis state 38', 'pp': 'Glycolysis state 39', 'p': 'Glycolysis state 40', 'p_er': 'Glycolysis state 41', 'co2': 'CO2', 'nad': 'NAD', 'nadh': 'NADH', 'atp_mito': 'Glycolysis state 45', 'adp_mito': 'Glycolysis state 46', 'gtp_mito': 'Glycolysis state 47', 'gdp_mito': 'Glycolysis state 48', 'nadh_mito': 'Glycolysis state 49', 'nad_mito': 'Glycolysis state 50'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_extracellular_glucose': ('glc_ext', 4.0, 'native SBML value', 'Initial condition for extracellular glucose. Maps to bundled SBML symbol `glc_ext`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_extracellular_lactate': ('lac_ext', 1.0, 'native SBML value', 'Initial condition for extracellular lactate. Maps to bundled SBML symbol `lac_ext`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glucose': ('glc', 4.92256221964406, 'native SBML value', 'Initial condition for glucose. Maps to bundled SBML symbol `glc`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_4': ('glc6p', 0.189929897759633, 'native SBML value', 'Initial condition for glycolysis state 4. Maps to bundled SBML symbol `glc6p`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_5': ('glc1p', 0.0117240677629403, 'native SBML value', 'Initial condition for glycolysis state 5. Maps to bundled SBML symbol `glc1p`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'extracellular_glucose': ('glc_ext', 'native SBML value', 'Extracellular Glucose. Maps to SBML symbol `glc_ext`.'), 'extracellular_lactate': ('lac_ext', 'native SBML value', 'Extracellular Lactate. Maps to SBML symbol `lac_ext`.'), 'glucose': ('glc', 'native SBML value', 'Glucose. Maps to SBML symbol `glc`.'), 'glycolysis_state_4': ('glc6p', 'native SBML value', 'Glycolysis state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `glc6p`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glycolysis_state_5': ('glc1p', 'native SBML value', 'Glycolysis state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `glc1p`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/BIOMD0000000633.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
