# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Davies2023 - Cholesterol Metabolism and Atherosclerosis Model."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Davies2023CholesterolMetabolismAndAtheroscleModel2306300001Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Davies2023 - Cholesterol Metabolism and Atherosclerosis Model."""

    _SBML_ID = 'MODEL2306300001'
    _TITLE = 'Davies2023 - Cholesterol Metabolism and Atherosclerosis Model'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'species_2': 'lipid_metabolism_state_1', 'species_4': 'lipid_metabolism_state_2', 'species_5': 'lipid_metabolism_state_3', 'species_7': 'lipid_metabolism_state_4', 'species_10': 'lipid_metabolism_state_5', 'species_11': 'lipid_metabolism_state_6', 'species_13': 'lipid_metabolism_state_7', 'species_14': 'lipid_metabolism_state_8', 'species_15': 'lipid_metabolism_state_9', 'species_17': 'lipid_metabolism_state_10', 'species_18': 'lipid_metabolism_state_11', 'species_21': 'lipid_metabolism_state_12', 'species_22': 'lipid_metabolism_state_13', 'species_23': 'lipid_metabolism_state_14', 'species_24': 'lipid_metabolism_state_15', 'species_25': 'lipid_metabolism_state_16', 'species_28': 'lipid_metabolism_state_17', 'species_30': 'lipid_metabolism_state_18', 'species_31': 'lipid_metabolism_state_19', 'species_33': 'lipid_metabolism_state_20', 'species_34': 'srb1', 'LDL': 'lipid_metabolism_state_22', 'oxLDL': 'lipid_metabolism_state_23', 'TINF': 'lipid_metabolism_state_24', 'TAINF': 'lipid_metabolism_state_25', 'MP': 'lipid_metabolism_state_26', 'PLAQUE': 'lipid_metabolism_state_27', 'Bcells': 'lipid_metabolism_state_28', 'HDL': 'lipid_metabolism_state_29'}
    _OBSERVABLES = ['species_2', 'species_4', 'species_5', 'species_7', 'species_10', 'species_11', 'species_13', 'species_14', 'species_15', 'species_17', 'species_18', 'species_21', 'species_22', 'species_23', 'species_24', 'species_25', 'species_28', 'species_30', 'species_31', 'species_33', 'species_34', 'LDL', 'oxLDL', 'TINF', 'TAINF', 'MP', 'PLAQUE', 'Bcells', 'HDL']
    _SPECIES_LABELS = {'species_2': 'Lipid Metabolism state 1', 'species_4': 'Lipid Metabolism state 2', 'species_5': 'Lipid Metabolism state 3', 'species_7': 'Lipid Metabolism state 4', 'species_10': 'Lipid Metabolism state 5', 'species_11': 'Lipid Metabolism state 6', 'species_13': 'Lipid Metabolism state 7', 'species_14': 'Lipid Metabolism state 8', 'species_15': 'Lipid Metabolism state 9', 'species_17': 'Lipid Metabolism state 10', 'species_18': 'Lipid Metabolism state 11', 'species_21': 'Lipid Metabolism state 12', 'species_22': 'Lipid Metabolism state 13', 'species_23': 'Lipid Metabolism state 14', 'species_24': 'Lipid Metabolism state 15', 'species_25': 'Lipid Metabolism state 16', 'species_28': 'Lipid Metabolism state 17', 'species_30': 'Lipid Metabolism state 18', 'species_31': 'Lipid Metabolism state 19', 'species_33': 'Lipid Metabolism state 20', 'species_34': 'Srb1', 'LDL': 'Lipid Metabolism state 22', 'oxLDL': 'Lipid Metabolism state 23', 'TINF': 'Lipid Metabolism state 24', 'TAINF': 'Lipid Metabolism state 25', 'MP': 'Lipid Metabolism state 26', 'PLAQUE': 'Lipid Metabolism state 27', 'Bcells': 'Lipid Metabolism state 28', 'HDL': 'Lipid Metabolism state 29'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_lipid_metabolism_state_1': ('species_2', 3150.0, 'native SBML value', 'Initial condition for lipid metabolism state 1. Maps to bundled SBML symbol `species_2`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_lipid_metabolism_state_2': ('species_4', 400.0, 'native SBML value', 'Initial condition for lipid metabolism state 2. Maps to bundled SBML symbol `species_4`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_lipid_metabolism_state_3': ('species_5', 467.0, 'native SBML value', 'Initial condition for lipid metabolism state 3. Maps to bundled SBML symbol `species_5`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_lipid_metabolism_state_4': ('species_7', 60000.0, 'native SBML value', 'Initial condition for lipid metabolism state 4. Maps to bundled SBML symbol `species_7`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_lipid_metabolism_state_5': ('species_10', 100.0, 'native SBML value', 'Initial condition for lipid metabolism state 5. Maps to bundled SBML symbol `species_10`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'lipid_metabolism_state_1': ('species_2', 'native SBML value', 'Lipid Metabolism state 1; conservative display label for an abstract SBML state variable. Maps to SBML symbol `species_2`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'lipid_metabolism_state_2': ('species_4', 'native SBML value', 'Lipid Metabolism state 2; conservative display label for an abstract SBML state variable. Maps to SBML symbol `species_4`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'lipid_metabolism_state_3': ('species_5', 'native SBML value', 'Lipid Metabolism state 3; conservative display label for an abstract SBML state variable. Maps to SBML symbol `species_5`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'lipid_metabolism_state_4': ('species_7', 'native SBML value', 'Lipid Metabolism state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `species_7`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'lipid_metabolism_state_5': ('species_10', 'native SBML value', 'Lipid Metabolism state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `species_10`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/MODEL2306300001.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
