# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Jeon2018 - Enzyme clustering in Glucose metabolism."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Jeon2018EnzymeClusteringInGlucoseMetabolismBiomd0000001055Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Jeon2018 - Enzyme clustering in Glucose metabolism."""

    _SBML_ID = 'BIOMD0000001055'
    _TITLE = 'Jeon2018 - Enzyme clustering in Glucose metabolism'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'Glucose': 'glycolysis_state_1', 'Fructose_6_Phosphate': 'fructose_6_phosphate', 'Fructose_1_6_Bisphosphate': 'fructose_1_6_bisphosphate', '_3_Phosphoglycerate': 'observable_3_phosphoglycerate', 'Phosphoenolpyruvate': 'glycolysis_state_5', 'Pyruvate': 'glycolysis_state_6', 'Oxaloacetate': 'glycolysis_state_7', 'Metabolic_outcome_of_Pentose_Phosphate_Shunt': 'metabolic_outcome_of_pentose_phosphate_shunt', 'Metabolic_outcome_of_Serine_Biosynthesis_Flux': 'metabolic_outcome_of_serine_biosynthesis_flux', 'Metabolic_outcome_of_Glycolytic_Flux': 'metabolic_outcome_of_glycolytic_flux', 'Phosphofructokinase_1': 'phosphofructokinase_1', 'Fructose_1_6_Bisphosphatase': 'fructose_1_6_bisphosphatase', 'Large_sized_enzyme_clusters': 'large_sized_enzyme_clusters', 'Medium_sized_enzyme_clusters': 'medium_sized_enzyme_clusters', 'Small_sized_enzyme_clusters': 'small_sized_enzyme_clusters', 'Pyruvate_Kinase_M2_dimers': 'pyruvate_kinase_m2_dimers', 'Phosphoenolpyruvate_Carboxykinase_1': 'phosphoenolpyruvate_carboxykinase_1', 'Glycosylated_Phosphofructokinase': 'glycosylated_phosphofructokinase', 'Pyruvate_Kinase_M2_tetramers': 'pyruvate_kinase_m2_tetramers'}
    _OBSERVABLES = ['Glucose', 'Fructose_6_Phosphate', 'Fructose_1_6_Bisphosphate', '_3_Phosphoglycerate', 'Phosphoenolpyruvate', 'Pyruvate', 'Oxaloacetate', 'Metabolic_outcome_of_Pentose_Phosphate_Shunt', 'Metabolic_outcome_of_Serine_Biosynthesis_Flux', 'Metabolic_outcome_of_Glycolytic_Flux', 'Phosphofructokinase_1', 'Fructose_1_6_Bisphosphatase', 'Large_sized_enzyme_clusters', 'Medium_sized_enzyme_clusters', 'Small_sized_enzyme_clusters', 'Pyruvate_Kinase_M2_dimers', 'Phosphoenolpyruvate_Carboxykinase_1', 'Glycosylated_Phosphofructokinase', 'Pyruvate_Kinase_M2_tetramers']
    _SPECIES_LABELS = {'Glucose': 'Glycolysis state 1', 'Fructose_6_Phosphate': 'Fructose 6 Phosphate', 'Fructose_1_6_Bisphosphate': 'Fructose 1 6 Bisphosphate', '_3_Phosphoglycerate': '3 Phosphoglycerate', 'Phosphoenolpyruvate': 'Glycolysis state 5', 'Pyruvate': 'Glycolysis state 6', 'Oxaloacetate': 'Glycolysis state 7', 'Metabolic_outcome_of_Pentose_Phosphate_Shunt': 'Metabolic Outcome Of Pentose Phosphate Shunt', 'Metabolic_outcome_of_Serine_Biosynthesis_Flux': 'Metabolic Outcome Of Serine Biosynthesis Flux', 'Metabolic_outcome_of_Glycolytic_Flux': 'Metabolic Outcome Of Glycolytic Flux', 'Phosphofructokinase_1': 'Phosphofructokinase 1', 'Fructose_1_6_Bisphosphatase': 'Fructose 1 6 Bisphosphatase', 'Large_sized_enzyme_clusters': 'Large Sized Enzyme Clusters', 'Medium_sized_enzyme_clusters': 'Medium Sized Enzyme Clusters', 'Small_sized_enzyme_clusters': 'Small Sized Enzyme Clusters', 'Pyruvate_Kinase_M2_dimers': 'Pyruvate Kinase M2 Dimers', 'Phosphoenolpyruvate_Carboxykinase_1': 'Phosphoenolpyruvate Carboxykinase 1', 'Glycosylated_Phosphofructokinase': 'Glycosylated Phosphofructokinase', 'Pyruvate_Kinase_M2_tetramers': 'Pyruvate Kinase M2 Tetramers'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_glycolysis_state_1': ('Glucose', 0.01, 'native SBML value', 'Initial condition for glycolysis state 1. Maps to bundled SBML symbol `Glucose`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_fructose_6_phosphate': ('Fructose_6_Phosphate', 0.01, 'native SBML value', 'Initial condition for fructose 6 phosphate. Maps to bundled SBML symbol `Fructose_6_Phosphate`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_fructose_1_6_bisphosphate': ('Fructose_1_6_Bisphosphate', 0.01, 'native SBML value', 'Initial condition for fructose 1 6 bisphosphate. Maps to bundled SBML symbol `Fructose_1_6_Bisphosphate`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_observable_3_phosphoglycerate': ('_3_Phosphoglycerate', 0.01, 'native SBML value', 'Initial condition for observable 3 phosphoglycerate. Maps to bundled SBML symbol `_3_Phosphoglycerate`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glycolysis_state_5': ('Phosphoenolpyruvate', 0.01, 'native SBML value', 'Initial condition for glycolysis state 5. Maps to bundled SBML symbol `Phosphoenolpyruvate`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'glycolysis_state_1': ('Glucose', 'native SBML value', 'Glycolysis state 1; conservative display label for an abstract SBML state variable. Maps to SBML symbol `Glucose`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'fructose_6_phosphate': ('Fructose_6_Phosphate', 'native SBML value', 'Fructose 6 Phosphate. Maps to SBML symbol `Fructose_6_Phosphate`.'), 'fructose_1_6_bisphosphate': ('Fructose_1_6_Bisphosphate', 'native SBML value', 'Fructose 1 6 Bisphosphate. Maps to SBML symbol `Fructose_1_6_Bisphosphate`.'), 'observable_3_phosphoglycerate': ('_3_Phosphoglycerate', 'native SBML value', '3 Phosphoglycerate. Maps to SBML symbol `_3_Phosphoglycerate`.'), 'glycolysis_state_5': ('Phosphoenolpyruvate', 'native SBML value', 'Glycolysis state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `Phosphoenolpyruvate`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/BIOMD0000001055.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
