# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Kotte2010_Ecoli_Metabolic_Adaption."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Kotte2010EcoliMetabolicAdaptionBiomd0000000244Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Kotte2010_Ecoli_Metabolic_Adaption."""

    _SBML_ID = 'BIOMD0000000244'
    _TITLE = 'Kotte2010_Ecoli_Metabolic_Adaption'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'BM': 'microbial_metabolism_state_1', 'ACT': 'microbial_metabolism_state_2', 'GLC': 'glucose', 'ACoA': 'microbial_metabolism_state_4', 'AKG': 'microbial_metabolism_state_5', 'cAMP': 'cytosolic_amp', 'FBP': 'fructose_bisphosphate', 'G6P': 'glucose_6_phosphate', 'GLX': 'microbial_metabolism_state_9', 'ICT': 'microbial_metabolism_state_10', 'MAL': 'microbial_metabolism_state_11', 'OAA': 'microbial_metabolism_state_12', 'PEP': 'phosphoenolpyruvate', 'PG3': 'microbial_metabolism_state_14', 'PYR': 'pyruvate', 'AceA': 'microbial_metabolism_state_16', 'AceB': 'blood_ace', 'AceK': 'microbial_metabolism_state_18', 'Acoa2act': 'microbial_metabolism_state_19', 'Acs': 'microbial_metabolism_state_20', 'Akg2mal': 'microbial_metabolism_state_21', 'CAMPdegr': 'microbial_metabolism_state_22', 'Cya': 'microbial_metabolism_state_23', 'Emp': 'microbial_metabolism_state_24', 'Eno': 'microbial_metabolism_state_25', 'Fdp': 'microbial_metabolism_state_26', 'GltA': 'microbial_metabolism_state_27', 'Icd': 'microbial_metabolism_state_28', 'Icd_P': 'microbial_metabolism_state_29', 'Mdh': 'microbial_metabolism_state_30', 'Me': 'microbial_metabolism_state_31', 'PckA': 'microbial_metabolism_state_32', 'Pdh': 'microbial_metabolism_state_33', 'PfkA': 'microbial_metabolism_state_34', 'Ppc': 'microbial_metabolism_state_35', 'PpsA': 'microbial_metabolism_state_36', 'PykF': 'microbial_metabolism_state_37', 'Cra': 'microbial_metabolism_state_38', 'CraFBP': 'microbial_metabolism_state_39', 'Crp': 'microbial_metabolism_state_40', 'CrpcAMP': 'microbial_metabolism_state_41', 'IclR': 'microbial_metabolism_state_42', 'PdhR': 'microbial_metabolism_state_43', 'PdhRPYR': 'microbial_metabolism_state_44', 'EIIA': 'microbial_metabolism_state_45', 'EIIA_P': 'microbial_metabolism_state_46', 'EIICB': 'microbial_metabolism_state_47'}
    _OBSERVABLES = ['BM', 'ACT', 'GLC', 'ACoA', 'AKG', 'cAMP', 'FBP', 'G6P', 'GLX', 'ICT', 'MAL', 'OAA', 'PEP', 'PG3', 'PYR', 'AceA', 'AceB', 'AceK', 'Acoa2act', 'Acs', 'Akg2mal', 'CAMPdegr', 'Cya', 'Emp', 'Eno', 'Fdp', 'GltA', 'Icd', 'Icd_P', 'Mdh', 'Me', 'PckA', 'Pdh', 'PfkA', 'Ppc', 'PpsA', 'PykF', 'Cra', 'CraFBP', 'Crp', 'CrpcAMP', 'IclR', 'PdhR', 'PdhRPYR', 'EIIA', 'EIIA_P', 'EIICB']
    _SPECIES_LABELS = {'BM': 'Microbial Metabolism state 1', 'ACT': 'Microbial Metabolism state 2', 'GLC': 'Glucose', 'ACoA': 'Microbial Metabolism state 4', 'AKG': 'Microbial Metabolism state 5', 'cAMP': 'Cytosolic AMP', 'FBP': 'Fructose Bisphosphate', 'G6P': 'Glucose 6 Phosphate', 'GLX': 'Microbial Metabolism state 9', 'ICT': 'Microbial Metabolism state 10', 'MAL': 'Microbial Metabolism state 11', 'OAA': 'Microbial Metabolism state 12', 'PEP': 'Phosphoenolpyruvate', 'PG3': 'Microbial Metabolism state 14', 'PYR': 'Pyruvate', 'AceA': 'Microbial Metabolism state 16', 'AceB': 'Blood ACE', 'AceK': 'Microbial Metabolism state 18', 'Acoa2act': 'Microbial Metabolism state 19', 'Acs': 'Microbial Metabolism state 20', 'Akg2mal': 'Microbial Metabolism state 21', 'CAMPdegr': 'Microbial Metabolism state 22', 'Cya': 'Microbial Metabolism state 23', 'Emp': 'Microbial Metabolism state 24', 'Eno': 'Microbial Metabolism state 25', 'Fdp': 'Microbial Metabolism state 26', 'GltA': 'Microbial Metabolism state 27', 'Icd': 'Microbial Metabolism state 28', 'Icd_P': 'Microbial Metabolism state 29', 'Mdh': 'Microbial Metabolism state 30', 'Me': 'Microbial Metabolism state 31', 'PckA': 'Microbial Metabolism state 32', 'Pdh': 'Microbial Metabolism state 33', 'PfkA': 'Microbial Metabolism state 34', 'Ppc': 'Microbial Metabolism state 35', 'PpsA': 'Microbial Metabolism state 36', 'PykF': 'Microbial Metabolism state 37', 'Cra': 'Microbial Metabolism state 38', 'CraFBP': 'Microbial Metabolism state 39', 'Crp': 'Microbial Metabolism state 40', 'CrpcAMP': 'Microbial Metabolism state 41', 'IclR': 'Microbial Metabolism state 42', 'PdhR': 'Microbial Metabolism state 43', 'PdhRPYR': 'Microbial Metabolism state 44', 'EIIA': 'Microbial Metabolism state 45', 'EIIA_P': 'Microbial Metabolism state 46', 'EIICB': 'Microbial Metabolism state 47'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_microbial_metabolism_state_1': ('BM', 0.03, 'native SBML value', 'Initial condition for microbial metabolism state 1. Maps to bundled SBML symbol `BM`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_microbial_metabolism_state_2': ('ACT', 0.0, 'native SBML value', 'Initial condition for microbial metabolism state 2. Maps to bundled SBML symbol `ACT`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_glucose': ('GLC', 4.8, 'native SBML value', 'Initial condition for glucose. Maps to bundled SBML symbol `GLC`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_microbial_metabolism_state_4': ('ACoA', 0.351972298, 'native SBML value', 'Initial condition for microbial metabolism state 4. Maps to bundled SBML symbol `ACoA`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_microbial_metabolism_state_5': ('AKG', 0.191190619, 'native SBML value', 'Initial condition for microbial metabolism state 5. Maps to bundled SBML symbol `AKG`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'microbial_metabolism_state_1': ('BM', 'native SBML value', 'Microbial Metabolism state 1; conservative display label for an abstract SBML state variable. Maps to SBML symbol `BM`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'microbial_metabolism_state_2': ('ACT', 'native SBML value', 'Microbial Metabolism state 2; conservative display label for an abstract SBML state variable. Maps to SBML symbol `ACT`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'glucose': ('GLC', 'native SBML value', 'Glucose. Maps to SBML symbol `GLC`.'), 'microbial_metabolism_state_4': ('ACoA', 'native SBML value', 'Microbial Metabolism state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `ACoA`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'microbial_metabolism_state_5': ('AKG', 'native SBML value', 'Microbial Metabolism state 5; conservative display label for an abstract SBML state variable. Maps to SBML symbol `AKG`. Exact metabolite identity is not encoded in the bundled SBML metadata.')}

    def __init__(self, model_path: str = 'data/BIOMD0000000244.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
