# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: Apache-2.0
"""Tellurium-backed wrapper for Reyes-Palomares2012 - a combined model hepatic polyamine and sulfur aminoacid metabolism - version2."""

from __future__ import annotations

from biosim.contrib.sbml import TelluriumSBMLBioModule


class ReyesPalomares2012ACombinedModelHepaticPolBiomd0000000450Model(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Reyes-Palomares2012 - a combined model hepatic polyamine and sulfur aminoacid metabolism - version2."""

    _SBML_ID = 'BIOMD0000000450'
    _TITLE = 'Reyes-Palomares2012 - a combined model hepatic polyamine and sulfur aminoacid metabolism - version2'
    _TIME_UNIT = 'model_time'
    _OBSERVABLE_STRATEGY = 'species'
    _EXPOSE_INTEGRATION_STEP_INPUT = False
    _SPECIES_LABELS_OUTPUT_NAME = 'observable_labels'
    _SUMMARY_OUTPUT_NAME = 'run_summary'
    _STATE_OUTPUT_NAME = 'observable_values'
    _STATE_OUTPUT_ALIASES = {'b_gly': 'b_glycine', 'b_glu': 'b_glutamate', 'b_cys': 'b_cysteine', 'b_gsg': 'metabolic_pathway_state_4', 'b_gsh': 'blood_glutathione', 'c_thf': 'cytosolic_tetrahydrofolate', 'c_5mf': 'metabolic_pathway_state_7', 'c_2cf': 'metabolic_pathway_state_8', 'c_1cf': 'metabolic_pathway_state_9', 'c_10f': 'metabolic_pathway_state_10', 'c_dhf': 'cytosolic_dihydrofolate', 'aic': 'metabolic_pathway_state_12', 'c_glu': 'c_glutamate', 'c_cys': 'c_cysteine', 'glc': 'glutamyl_cysteine', 'c_gly': 'c_glycine', 'c_gsg': 'metabolic_pathway_state_17', 'c_gsh': 'cytosolic_glutathione', 'cyt': 'cystathionine', 'hcy': 'homocysteine', 'c_ser': 'c_serine', 'sah': 's_adenosylhomocysteine', 'sam': 's_adenosylmethionine', 'met': 'c_methionine', 'c_coo': 'c_formate', 'species_1': 'metabolic_pathway_state_26', 'species_2': 'putrescine', 'species_3': 'metabolic_pathway_state_28', 'species_4': 'spermidine', 'species_5': 'acetylspermine', 'species_6': 'acetylspermidine', 'species_8': 'metabolic_pathway_state_32', 'species_9': 'coa', 'm_thf': 'mitochondrial_tetrahydrofolate', 'm_2cf': 'metabolic_pathway_state_35', 'm_1cf': 'metabolic_pathway_state_36', 'm_10f': 'metabolic_pathway_state_37', 'm_ser': 'm_serine', 'm_gly': 'm_glycine', 'm_coo': 'm_formate', 'src': 'sarcosine', 'dmg': 'dimethylglycine'}
    _OBSERVABLES = ['b_gly', 'b_glu', 'b_cys', 'b_gsg', 'b_gsh', 'c_thf', 'c_5mf', 'c_2cf', 'c_1cf', 'c_10f', 'c_dhf', 'aic', 'c_glu', 'c_cys', 'glc', 'c_gly', 'c_gsg', 'c_gsh', 'cyt', 'hcy', 'c_ser', 'sah', 'sam', 'met', 'c_coo', 'species_1', 'species_2', 'species_3', 'species_4', 'species_5', 'species_6', 'species_8', 'species_9', 'm_thf', 'm_2cf', 'm_1cf', 'm_10f', 'm_ser', 'm_gly', 'm_coo', 'src', 'dmg']
    _SPECIES_LABELS = {'b_gly': 'B Glycine', 'b_glu': 'B Glutamate', 'b_cys': 'B Cysteine', 'b_gsg': 'Metabolic Pathway state 4', 'b_gsh': 'Blood Glutathione', 'c_thf': 'Cytosolic Tetrahydrofolate', 'c_5mf': 'Metabolic Pathway state 7', 'c_2cf': 'Metabolic Pathway state 8', 'c_1cf': 'Metabolic Pathway state 9', 'c_10f': 'Metabolic Pathway state 10', 'c_dhf': 'Cytosolic Dihydrofolate', 'aic': 'Metabolic Pathway state 12', 'c_glu': 'C Glutamate', 'c_cys': 'C Cysteine', 'glc': 'Glutamyl Cysteine', 'c_gly': 'C Glycine', 'c_gsg': 'Metabolic Pathway state 17', 'c_gsh': 'Cytosolic Glutathione', 'cyt': 'Cystathionine', 'hcy': 'Homocysteine', 'c_ser': 'C Serine', 'sah': 'S adenosylhomocysteine', 'sam': 'S adenosylmethionine', 'met': 'C Methionine', 'c_coo': 'C Formate', 'species_1': 'Metabolic Pathway state 26', 'species_2': 'Putrescine', 'species_3': 'Metabolic Pathway state 28', 'species_4': 'Spermidine', 'species_5': 'Acetylspermine', 'species_6': 'Acetylspermidine', 'species_8': 'Metabolic Pathway state 32', 'species_9': 'CoA', 'm_thf': 'Mitochondrial Tetrahydrofolate', 'm_2cf': 'Metabolic Pathway state 35', 'm_1cf': 'Metabolic Pathway state 36', 'm_10f': 'Metabolic Pathway state 37', 'm_ser': 'M Serine', 'm_gly': 'M Glycine', 'm_coo': 'M Formate', 'src': 'Sarcosine', 'dmg': 'Dimethylglycine'}
    _PARAMETER_INPUTS = {}
    _INITIAL_CONDITION_INPUTS = {'initial_b_glycine': ('b_gly', 218.733171504338, 'native SBML value', 'Initial condition for b glycine. Maps to bundled SBML symbol `b_gly`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_b_glutamate': ('b_glu', 60.4651616225031, 'native SBML value', 'Initial condition for b glutamate. Maps to bundled SBML symbol `b_glu`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_b_cysteine': ('b_cys', 183.099466381356, 'native SBML value', 'Initial condition for b cysteine. Maps to bundled SBML symbol `b_cys`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_metabolic_pathway_state_4': ('b_gsg', 0.472632922783833, 'native SBML value', 'Initial condition for metabolic pathway state 4. Maps to bundled SBML symbol `b_gsg`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.'), 'initial_blood_glutathione': ('b_gsh', 12.5470655822207, 'native SBML value', 'Initial condition for blood glutathione. Maps to bundled SBML symbol `b_gsh`. Applied before the Tellurium simulation starts; this does not change kinetic parameters or equations.')}
    _HEADLINE_OUTPUTS = {'b_glycine': ('b_gly', 'native SBML value', 'B Glycine. Maps to SBML symbol `b_gly`.'), 'b_glutamate': ('b_glu', 'native SBML value', 'B Glutamate. Maps to SBML symbol `b_glu`.'), 'b_cysteine': ('b_cys', 'native SBML value', 'B Cysteine. Maps to SBML symbol `b_cys`.'), 'metabolic_pathway_state_4': ('b_gsg', 'native SBML value', 'Metabolic Pathway state 4; conservative display label for an abstract SBML state variable. Maps to SBML symbol `b_gsg`. Exact metabolite identity is not encoded in the bundled SBML metadata.'), 'blood_glutathione': ('b_gsh', 'native SBML value', 'Blood Glutathione. Maps to SBML symbol `b_gsh`.')}

    def __init__(self, model_path: str = 'data/BIOMD0000000450.xml', integration_step: float = 0.1) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
